<?php
class AuxiliaryFunctions {
  public function __construct() {
  }

  public function formatName($name) {
    return strtoupper(substr($name, 0, 1)) . substr($name, 1);
  }

  public function formatId($content) {
    $aux = array_filter(explode('/', $content));
    return intval($aux[count($aux)]);
  }

  public function translateAbilityName($ability) {
    $translate_ability = [
      'stench'           => 'Fedor',
      'drizzle'          => 'Chuvisco',
      'speed-boost'      => 'Acelerador',
      'battle-armor'     => 'Armadura de Batalha',
      'sturdy'           => 'Resistência',
      'damp'             => 'Umidade',
      'limber'           => 'Flexibilidade',
      'sand-veil'        => 'Véu de Areia',
      'static'           => 'Estática',
      'volt-absorb'      => 'Absorve-Volts',
      'water-absorb'     => 'Absorve-Água',
      'oblivious'        => 'Inconsciência',
      'cloud-nine'       => 'Nuvem Nove',
      'compound-eyes'    => 'Olhos Compostos',
      'insomnia'         => 'Insônia',
      'color-change'     => 'Mudança de Cor',
      'immunity'         => 'Imunidade',
      'flash-fire'       => 'Fogo Recebido',
      'shield-dust'      => 'Escudo de Poeira',
      'own-tempo'        => 'Ritmo Próprio',
      'suction-cups'     => 'Ventosas',
      'intimidate'       => 'Intimidar',
      'shadow-tag'       => 'Etiqueta Sombria',
      'rough-skin'       => 'Pele Áspera',
      'wonder-guard'     => 'Guarda Maravilhosa',
      'levitate'         => 'Levitação',
      'effect-spore'     => 'Efeito Espora',
      'synchronize'      => 'Sincronismo',
      'clear-body'       => 'Corpo Limpo',
      'natural-cure'     => 'Cura Natura',
      'lightning-rod'    => 'Vara-Relâmpago',
      'serene-grace'     => 'Graça Serena',
      'swift-swim'       => 'Nado Rápido',
      'chlorophyll'      => 'Clorofila',
      'illuminate'       => 'Iluminar',
      'trace'            => 'Rastro',
      'huge-power'       => 'Poder Imenso',
      'poison-point'     => 'Ponto de Veneno',
      'inner-focus'      => 'Concentração Interna',
      'magma-armor'      => 'Armadura de Magm',
      'water-veil'       => 'Véu de Água',
      'magnet-pull'      => 'Magnetismo',
      'soundproof'       => 'Insonorização',
      'rain-dish'        => 'Chuva do Desejo',
      'sand-stream'      => 'Córrego de Areia',
      'pressure'         => 'Pressão',
      'thick-fat'        => 'Gordura Espessa',
      'early-bird'       => 'Passáro Precoce',
      'flame-body'       => 'Corpo em Chamas',
      'run-away'         => 'Fuga',
      'keen-eye'         => 'Olho Entusiasmado',
      'hyper-cutter'     => 'Hiper Cortador',
      'pickup'           => 'Capturar',
      'truant'           => 'Preguiça',
      'hustle'           => 'Entusiasmo',
      'cute-charm'       => 'Charme Gracioso',
      'plus'             => 'Mais',
      'minus'            => 'Menos',
      'forecast'         => 'Previsão do Tempo',
      'sticky-hold'      => 'Viscosidade',
      'shed-skin'        => 'Pele vertente',
      'guts'             => 'Músculos',
      'marvel-scale'     => 'Escama Maravilha',
      'liquid-ooze'      => 'Lodo Líquido',
      'overgrow'         => 'Super Crescimento',
      'blaze'            => 'Incêndio',
      'torrent'          => 'Dilúvi',
      'swarm'            => 'Enxame',
      'rock-head'        => 'Cabeça de Pedra',
      'drought'          => 'Seca/Calor Desértico',
      'arena-trap'       => 'Arena-Armadilha',
      'vital-spirit'     => 'Espírito Vital',
      'white-smoke'      => 'Fumo Branco',
      'pure-power'       => 'Poder Puro',
      'shell-armor'      => 'Armadura de Concha',
      'air-lock'         => 'Bloqueio Aéreo',
      'tangled-feet'     => 'Pés Laçados',
      'motor-drive'      => 'Impulso Motor',
      'rivalry'          => 'Rivalidade',
      'steadfast'        => 'Inabalável',
      'snow-cloak'       => 'Capa de Neve',
      'gluttony'         => 'Gulodice',
      'anger-point'      => 'Ponto de Raiva',
      'unburden'         => 'Sem Peso',
      'heatproof'        => 'À Prova de Calor',
      'simple'           => 'Simplificar',
      'dry-skin'         => 'Pele Seca',
      'download'         => 'Descarga',
      'iron-fist'        => 'Punho de Ferro',
      'poison-heal'      => 'Antídoto',
      'adaptability'     => 'Adaptabilidade',
      'skill-link'       => 'Liga Habilidade',
      'hydration'        => 'Hidratação',
      'solar-power'      => 'Poder Solar',
      'quick-feet'       => 'Pés Rápidos',
      'normalize'        => 'Normalidade',
      'sniper'           => 'Franco-Atirador',
      'magic-guard'      => 'Escudo Mágico',
      'no-guard'         => 'Sem Proteção',
      'stall'            => 'Adiar',
      'technician'       => 'Técnico',
      'leaf-guard'       => 'Guarda Folha',
      'klutz'            => 'Grosseria',
      'mold-breaker'     => 'Destruidor de Molde',
      'super-luck'       => 'Supersorte',
      'aftermath'        => 'Consequência',
      'anticipation'     => 'Antecipação',
      'forewarn'         => 'Profecia',
      'unaware'          => 'Ignorante',
      'tinted-lens'      => 'Olhos Escuros',
      'filter'           => 'Filtragem',
      'slow-start'       => 'Começo Lento',
      'scrappy'          => 'Transparência',
      'storm-drain'      => 'Drena-Tempestades',
      'ice-body'         => 'Corpo de Gelo',
      'solid-rock'       => 'Rocha Sólida',
      'snow-warning'     => 'Alerta de Neve',
      'honey-gather'     => 'Pegar Mel',
      'frisk'            => 'Bisbilhotar',
      'reckless'         => 'Imprudência',
      'multitype'        => 'Multitipo',
      'flower-gift'      => 'Presente da Flor',
      'bad-dreams'       => 'Pesadelos',
      'pickpocket'       => 'Furto',
      'sheer-force'      => 'Força Absoluta',
      'contrary'         => 'Contrário',
      'unnerve'          => 'Enervar',
      'defiant'          => 'Desafiante',
      'defeatist'        => 'Derrotável',
      'cursed-body'      => 'Corpo Amaldiçoado',
      'healer'           => 'Cura',
      'friend-guard'     => 'Proteção Amiga',
      'weak-armor'       => 'Armadura Fraca',
      'heavy-metal'      => 'Metal Pesado',
      'light-metal'      => 'Metal Leve',
      'multiscale'       => 'Multiescamas',
      'toxic-boost'      => 'Impulso Tóxico',
      'flare-boost'      => 'Impulso Ardente',
      'harvest'          => 'Colheita',
      'telepathy'        => 'Telepatia',
      'moody'            => 'Mal-Humor',
      'overcoat'         => 'Sobrecasaco',
      'poison-touch'     => 'Toque Venenoso',
      'regenerator'      => 'Regeneração',
      'big-pecks'        => 'Beijinhos',
      'sand-rush'        => 'Ímpeto Areia',
      'wonder-skin'      => 'Pele Maravilha',
      'analytic'         => 'Analítico',
      'illusion'         => 'Ilusão',
      'imposter'         => 'Impostor',
      'infiltrator'      => 'Infiltrado',
      'mummy'            => 'Múmia',
      'moxie'            => 'Arrogância',
      'justified'        => 'Justiceiro',
      'rattled'          => 'Covardia',
      'magic-bounce'     => 'Reflexo Mágico',
      'sap-sipper'       => 'Engolidor de Seiva',
      'prankster'        => 'Travessura',
      'sand-force'       => 'Força da Areia',
      'iron-barbs'       => 'Espinhos de Ferro',
      'zen-mode'         => 'Modo Zen',
      'victory-star'     => 'Estrela da Vitória',
      'turboblaze'       => 'Turbochama',
      'teravolt'         => 'Teravoltagem',
      'aroma-veil'       => 'Véu Vromático',
      'flower-veil'      => 'Véu de Flores',
      'cheek-pouch'      => 'Bolsa de Bochecha',
      'protean'          => 'Mutatipo',
      'fur-coat'         => 'Camada de Pelos',
      'magician'         => 'Mago',
      'bulletproof'      => 'À prova de balas',
      'competitive'      => 'Competitivo',
      'strong-jaw'       => 'Mandíbula Forte',
      'refrigerate'      => 'Refrigeração',
      'sweet-veil'       => 'Véu Doce',
      'stance-change'    => 'Mudança em Posição',
      'gale-wings'       => 'Asas de Vendaval',
      'mega-launcher'    => 'Megalançamento',
      'grass-pelt'       => 'Pele de Grama',
      'symbiosis'        => 'Simbiose',
      'tough-claws'      => 'Garra Dura',
      'pixilate'         => 'Pele de Fada',
      'gooey'            => 'Pegajoso',
      'aerilate'         => 'Arejar',
      'parental-bond'    => 'Vínculo Parental',
      'dark-aura'        => 'Aura Negra',
      'fairy-aura'       => 'Aura de Fada',
      'aura-break'       => 'Quebra de aura',
      'primordial-sea'   => 'Mar Primordial',
      'desolate-land'    => 'Área Desolada',
      'delta-stream'     => 'Corrente Delta',
      'stamina'          => 'Stamina',
      'wimp-out'         => 'Amarelar',
      'emergency-exit'   => 'Saída de Emergência',
      'water-compaction' => 'Compactação de Água',
      'merciless'        => 'Impiedoso',
      'shields-down'     => 'Escudos Abaixados',
      'stakeout'         => 'Tocaia',
      'water-bubble'     => 'Bolha de Água',
      'steelworker'      => 'Trabalhador de Aço',
      'berserk'          => 'Furioso',
      'slush-rush'       => 'Limpa-Neves',
      'long-reach'       => 'Longo Alcance',
      'liquid-voice'     => 'Voz Fluida',
      'triage'           => 'Triagem',
      'galvanize'        => 'Galvanizar',
      'surge-surfer'     => 'Cauda Surfista',
      'schooling'        => 'Cardume',
      'disguise'         => 'Disfarce',
      'battle-bond'      => 'Laço de Batalha',
      'power-construct'  => 'Construção de Poder',
      'corrosion'        => 'Corrosão',
      'comatose'         => 'Em Coma',
      'queenly-majesty'  => 'Presença Régia',
      'innards-out'      => 'Extensão de Vísceras',
      'dancer'           => 'Dançarino',
      'battery'          => 'Bateria',
      'fluffy'           => 'Macio',
      'dazzling'         => 'Ofuscante',
      'soul-heart'       => 'Coralma',
      'tangling-hair'    => 'Cabelo Desgrenhado',
      'receiver'         => 'Receptor',
      'power-of-alchemy' => 'Poder de Alquimia',
      'beast-boost'      => 'Impulso de Besta',
      'rks-system'       => 'Sistema RKS',
      'electric-surge'   => 'Eletrogênese',
      'psychic-surge'    => 'Onda Psíquica',
      'misty-surge'      => 'Onda de Névoa',
      'grassy-surge'     => 'Onda Gramínea',
      'full-metal-body'  => 'Corpo Metálico',
      'shadow-shield'    => 'Escudo Sombrio',
      'prism-armor'      => 'Armadura de Prisma',
      'neuroforce'       => 'Neuroforça',
      'intrepid-sword'   => 'Espada Intrépida',
      'dauntless-shield' => 'Escudo Destemido',
      'libero'           => 'Líbero',
      'ball-fetch'       => 'Pegar Bola',
      'cotton-down'      => 'Penugem de Algodão',
      'propeller-tail'   => 'Hélice de Cauda',
      'mirror-armor'     => 'Armadura Espelhada',
      'gulp-missile'     => 'Míssil de Gole',
      'stalwart'         => 'Robusto',
      'steam-engine'     => 'Motor à Vapor',
      'punk-rock'        => 'Punk Rock',
      'sand-spit'        => 'Cuspe de Areia',
      'ice-scales'       => 'Escamas de Gelo',
      'ripen'            => 'Maturação',
      'ice-face'         => 'Face de Gelo',
      'power-spot'       => 'Fonte de Energia',
      'mimicry'          => 'Mimetismo',
      'screen-cleaner'   => 'Limpa-Vidro',
      'steely-spirit'    => 'Espírito Férreo',
      'perish-body'      => 'Corpo Perecido',
      'wandering-spirit' => 'Espírito Errante',
      'gorilla-tactics'  => 'Táticas de Gorila',
      'neutralizing-gas' => 'Gás Neutralizador',
      'pastel-veil'      => 'Véu de Tons Pastéis',
      'hunger-switch'    => 'Troca da Fome',
      'quick-draw'       => 'Movimento Rápido',
      'unseen-fist'      => 'Punho Invisível',
      'curious-medicine' => 'Medicina Curiosa',
      'transistor'       => 'Transistor',
      'dragons-maw'      => 'Boca de Dragão',
      'chilling-neigh'   => 'Relincho Arrepiante',
      'grim-neigh'       => 'Relincho Cruel',
      'as-one-glastrier' => 'Como um Vidraceiro',
      'as-one-spectrier' => 'Como um Espectro',
      'lingering-aroma'  => 'Aroma Persistente',
      'seed-sower'       => 'Semeador de Sementes',
      'thermal-exchange' => 'Câmbio Termal',
      'anger-shell'      => 'Casca de Raiva',
      'purifying-salt'   => 'Sal Purificador',
      'well-baked-body'  => 'Corpo Bem Assado',
      'wind-rider'       => 'Cavaleiro do Vento',
      'guard-dog'        => 'Cão de Guarda',
      'rocky-payload'    => 'Carga Rochosa',
      'wind-power'       => 'Força do Vento',
      'zero-to-hero'     => 'De Zero a Herói',
      'commander'        => 'Comandante',
      'electromorphosis' => 'Eletromorfose',
      'protosynthesis'   => 'Protossíntese',
      'quark-drive'      => 'Condução de Quarks',
      'good-as-gold'     => 'bom como ouro',
      'vessel-of-ruin'   => 'Embarcação da Ruína',
      'sword-of-ruin'    => 'Espada da Ruína',
      'tablets-of-ruin'  => 'Tábuas da Ruína',
      'beads-of-ruin'    => 'contas de ruína',
      'orichalcum-pulse' => 'Pulso de Oricalco',
      'hadron-engine'    => 'Motor de Hádrons',
      'opportunist'      => 'Oportunista',
      'cud-chew'         => 'mastigar',
      'sharpness'        => 'Agudeza',
      'supreme-overlord' => 'Soberano Supremo',
      'costar'           => 'Co-estrela',
      'toxic-debris'     => 'Destroços Tóxicos',
      'armor-tail'       => 'cauda de armadura',
      'earth-eater'      => 'Comedor de Terra',
      'mycelium-might'   => 'Força de Micélio',
      'mountaineer'      => 'alpinista',
      'wave-rider'       => 'cavaleiro da onda',
      'skater'           => 'skatista',
      'thrust'           => 'empuxo',
      'perception'       => 'percepção',
      'parry'            => 'desviar-se',
      'instinct'         => 'instinto',
      'dodge'            => 'desviar',
      'jagged-edge'      => 'borda irregular',
      'frostbite'        => 'Queimadura por frio',
      'tenacity'         => 'tenacidade',
      'pride'            => 'orgulho',
      'deep-sleep'       => 'sono profundo',
      'power-nap'        => 'cochilo rápido',
      'spirit'           => 'espírito',
      'warm-blanket'     => 'cobertor quente',
      'gulp'             => 'gole',
      'herbivore'        => 'herbívoro',
      'sandpit'          => 'caixa de areia',
      'hot-blooded'      => 'sangue quente',
      'medic'            => 'médico',
      'life-force'       => 'força vital',
      'lunchbox'         => 'lancheira',
      'nurse'            => 'enfermeira',
      'melee'            => 'corpo a corpo',
      'sponge'           => 'esponja',
      'bodyguard'        => 'guarda-costas',
      'hero'             => 'herói',
      'last-bastion'     => 'último bastião',
      'stealth'          => 'furtivo',
      'vanguard'         => 'vanguarda',
      'nomad'            => 'nômade',
      'sequence'         => 'sequência',
      'grass-cloak'      => 'manto de grama',
      'celebrate'        => 'celebrate',
      'lullaby'          => 'canção de ninar',
      'calming'          => 'calmante',
      'daze'             => 'torpor',
      'frighten'         => 'assustar',
      'interference'     => 'interferência',
      'mood-maker'       => 'criador de humor',
      'confidence'       => 'confiança',
      'fortune'          => 'fortuna',
      'bonanza'          => 'bonança',
      'explode'          => 'explodir',
      'omnipotent'       => 'onipotente',
      'share'            => 'compartilhar',
      'black-hole'       => 'buraco negro',
      'shadow-dash'      => 'traço de sombra',
      'sprint'           => 'corrida',
      'disgust'          => 'desgosto',
      'high-rise'        => 'arranha-céus',
      'climber'          => 'alpinista',
      'flame-boost'      => 'impulso de chama',
      'aqua-boost'       => 'impulso aquático',
      'run-up'           => 'correr',
      'conqueror'        => 'conquistador',
      'shackle'          => 'manilha',
      'decoy'            => 'chamariz',
      'shield'           => 'escudo',
    ];
    
    return $translate_ability[$ability];
  }

  public function translateEggGroupName($eggGroup) {
    $translate_eggGroup = [
      "monster"       => "Monstro",
      "water1"        => "Água - Tipo 1",
      "bug"           => "Inseto",
      "flying"        => "Voador",
      "ground"        => "Terrestre",
      "fairy"         => "Fada",
      "plant"         => "Planta",
      "humanshape"    => "Forma Humana",
      "water3"        => "Água - Tipo 3",
      "mineral"       => "Mineral",
      "indeterminate" => "indeterminado",
      "water2"        => "Água - Tipo 2",
      "ditto"         => "Idem",
      "dragon"        => "Dragão",
      "no-eggs"       => "Sem Ovos"
    ];

    return $translate_eggGroup[$eggGroup];
  }

  public function translateGenderName($gender) {
    $translate_gender = [
      "female"     => "Feminino",
      "male"       => "Masculino",
      "genderless" => "Sem Gênero"
    ];

    return $translate_gender[$gender];
  }

  public function translateHabitatName($habitat) {
    $translate_habitat = [
      "cave"          => "caverna",
      "forest"        => "floresta",
      "grassland"     => "pastagem",
      "mountain"      => "montanha",
      "rare"          => "cru",
      "rough-terrain" => "terreno acidentado",
      "sea"           => "mar",
      "urban"         => "urbano",
      "waters-edge"   => "beira da água"
    ];

    return $translate_habitat[$habitat];
  }

  public function translateShapeName($shape) {
    $translate_shape = [
      "ball"      => "bola",
      "squiggle"  => "rabisco",
      "fish"      => "peixe",
      "arms"      => "braços",
      "blob"      => "bolha",
      "upright"   => "ereto",
      "legs"      => "pernas",
      "quadruped" => "quadrúpede",
      "wings"     => "asas",
      "tentacles" => "tentáculos",
      "heads"     => "cabeças",
      "humanoid"  => "humanóide",
      "bug-wings" => "asas de insetos",
      "armor"     => "armaduras"
    ];

    return $translate_shape[$shape];
  }

  public function translateStatName($stat) {
    $translate_stat = [
      "hp"              => "Pontos de Vida",
      "attack"          =>"Ataque",
      "defense"         => "Defesa",
      "special-attack"  => "Ataque Especial",
      "special-defense" => "Defesa Especial",
      "speed"           => "Velocidade",
      "accuracy"        => "Precisão",
      "evasion"         => "evasão"
    ];

    return $translate_stat[$stat];
  }

  public function translateTypeName($type) {
    $translate_types = [
      'bug'      => 'Inseto',
      'dark'     => 'Sombrio',
      'dragon'   => 'Dragão',
      'electric' => 'Elétrico',
      'fairy'    => 'Fada',
      'fighting' => 'Lutador',
      'fire'     => 'Fogo',
      'flying'   => 'Voador',
      'ghost'    => 'Fantasma',
      'grass'    => 'Planta',
      'ground'   => 'Terrestre',
      'ice'      => 'Gelo',
      'normal'   => 'Normal',
      'poison'   => 'Venenoso',
      'psychic'  => 'Psíquico',
      'rock'     => 'Pedra',
      'steel'    => 'Metálico',
      'water'    => 'Água',
      'unknown'  => 'Desconhecido',
      'shadow'   => 'Sombra'
    ];

    return $translate_types[$type];
  }
}
?>