<?php
$listOfWeaknesses = "Normal —|Normal;|Fire;|Water;|Electric;|Grass;|Ice;|Fighting;2|Poison;|Ground;|Flying;|Psychic;|Bug;|Rock;|Ghost;0|Dragon;|Dark;|Steel;|Fairy;
Normal Fire|Normal;|Fire;½|Water;2|Electric;|Grass;½|Ice;½|Fighting;2|Poison;|Ground;2|Flying;|Psychic;|Bug;½|Rock;2|Ghost;0|Dragon;|Dark;|Steel;½|Fairy;½
Normal Water|Normal;|Fire;½|Water;½|Electric;2|Grass;2|Ice;½|Fighting;2|Poison;|Ground;|Flying;|Psychic;|Bug;|Rock;|Ghost;0|Dragon;|Dark;|Steel;½|Fairy;
Normal Electric|Normal;|Fire;|Water;|Electric;½|Grass;|Ice;|Fighting;2|Poison;|Ground;2|Flying;½|Psychic;|Bug;|Rock;|Ghost;0|Dragon;|Dark;|Steel;½|Fairy;
Normal Grass|Normal;|Fire;2|Water;½|Electric;½|Grass;½|Ice;2|Fighting;2|Poison;2|Ground;½|Flying;2|Psychic;|Bug;2|Rock;|Ghost;0|Dragon;|Dark;|Steel;|Fairy;
Normal Ice|Normal;|Fire;2|Water;|Electric;|Grass;|Ice;½|Fighting;4|Poison;|Ground;|Flying;|Psychic;|Bug;|Rock;2|Ghost;0|Dragon;|Dark;|Steel;2|Fairy;
Normal Fighting|Normal;|Fire;|Water;|Electric;|Grass;|Ice;|Fighting;2|Poison;|Ground;|Flying;2|Psychic;2|Bug;½|Rock;½|Ghost;0|Dragon;|Dark;½|Steel;|Fairy;2
Normal Poison|Normal;|Fire;|Water;|Electric;|Grass;½|Ice;|Fighting;|Poison;½|Ground;2|Flying;|Psychic;2|Bug;½|Rock;|Ghost;0|Dragon;|Dark;|Steel;|Fairy;½
Normal Ground|Normal;|Fire;|Water;2|Electric;0|Grass;2|Ice;2|Fighting;2|Poison;½|Ground;|Flying;|Psychic;|Bug;|Rock;½|Ghost;0|Dragon;|Dark;|Steel;|Fairy;
Normal Flying|Normal;|Fire;|Water;|Electric;2|Grass;½|Ice;2|Fighting;|Poison;|Ground;0|Flying;|Psychic;|Bug;½|Rock;2|Ghost;0|Dragon;|Dark;|Steel;|Fairy;
Normal Psychic|Normal;|Fire;|Water;|Electric;|Grass;|Ice;|Fighting;|Poison;|Ground;|Flying;|Psychic;½|Bug;2|Rock;|Ghost;0|Dragon;|Dark;2|Steel;|Fairy;
Normal Bug|Normal;|Fire;2|Water;|Electric;|Grass;½|Ice;|Fighting;|Poison;|Ground;½|Flying;2|Psychic;|Bug;|Rock;2|Ghost;0|Dragon;|Dark;|Steel;|Fairy;
Normal Rock|Normal;½|Fire;½|Water;2|Electric;|Grass;2|Ice;|Fighting;4|Poison;½|Ground;2|Flying;½|Psychic;|Bug;|Rock;|Ghost;0|Dragon;|Dark;|Steel;2|Fairy;
Normal Ghost|Normal;0|Fire;|Water;|Electric;|Grass;|Ice;|Fighting;0|Poison;½|Ground;|Flying;|Psychic;|Bug;½|Rock;|Ghost;0|Dragon;|Dark;2|Steel;|Fairy;
Normal Dragon|Normal;|Fire;½|Water;½|Electric;½|Grass;½|Ice;2|Fighting;2|Poison;|Ground;|Flying;|Psychic;|Bug;|Rock;|Ghost;0|Dragon;2|Dark;|Steel;|Fairy;2
Normal Dark|Normal;|Fire;|Water;|Electric;|Grass;|Ice;|Fighting;4|Poison;|Ground;|Flying;|Psychic;0|Bug;2|Rock;|Ghost;0|Dragon;|Dark;½|Steel;|Fairy;2
Normal Steel|Normal;½|Fire;2|Water;|Electric;|Grass;½|Ice;½|Fighting;4|Poison;0|Ground;2|Flying;½|Psychic;½|Bug;½|Rock;½|Ghost;0|Dragon;½|Dark;|Steel;½|Fairy;½
Normal Fairy|Normal;|Fire;|Water;|Electric;|Grass;|Ice;|Fighting;|Poison;2|Ground;|Flying;|Psychic;|Bug;½|Rock;|Ghost;0|Dragon;0|Dark;½|Steel;2|Fairy;
Fire —|Normal;|Fire;½|Water;2|Electric;|Grass;½|Ice;½|Fighting;|Poison;|Ground;2|Flying;|Psychic;|Bug;½|Rock;2|Ghost;|Dragon;|Dark;|Steel;½|Fairy;½
Fire Normal|Normal;|Fire;½|Water;2|Electric;|Grass;½|Ice;½|Fighting;2|Poison;|Ground;2|Flying;|Psychic;|Bug;½|Rock;2|Ghost;0|Dragon;|Dark;|Steel;½|Fairy;½
Fire Water|Normal;|Fire;¼|Water;|Electric;2|Grass;|Ice;¼|Fighting;|Poison;|Ground;2|Flying;|Psychic;|Bug;½|Rock;2|Ghost;|Dragon;|Dark;|Steel;¼|Fairy;½
Fire Electric|Normal;|Fire;½|Water;2|Electric;½|Grass;½|Ice;½|Fighting;|Poison;|Ground;4|Flying;½|Psychic;|Bug;½|Rock;2|Ghost;|Dragon;|Dark;|Steel;¼|Fairy;½
Fire Grass|Normal;|Fire;|Water;|Electric;½|Grass;¼|Ice;|Fighting;|Poison;2|Ground;|Flying;2|Psychic;|Bug;|Rock;2|Ghost;|Dragon;|Dark;|Steel;½|Fairy;½
Fire Ice|Normal;|Fire;|Water;2|Electric;|Grass;½|Ice;¼|Fighting;2|Poison;|Ground;2|Flying;|Psychic;|Bug;½|Rock;4|Ghost;|Dragon;|Dark;|Steel;|Fairy;½
Fire Fighting|Normal;|Fire;½|Water;2|Electric;|Grass;½|Ice;½|Fighting;|Poison;|Ground;2|Flying;2|Psychic;2|Bug;¼|Rock;|Ghost;|Dragon;|Dark;½|Steel;½|Fairy;
Fire Poison|Normal;|Fire;½|Water;2|Electric;|Grass;¼|Ice;½|Fighting;½|Poison;½|Ground;4|Flying;|Psychic;2|Bug;¼|Rock;2|Ghost;|Dragon;|Dark;|Steel;½|Fairy;¼
Fire Ground|Normal;|Fire;½|Water;4|Electric;0|Grass;|Ice;|Fighting;|Poison;½|Ground;2|Flying;|Psychic;|Bug;½|Rock;|Ghost;|Dragon;|Dark;|Steel;½|Fairy;½
Fire Flying|Normal;|Fire;½|Water;2|Electric;2|Grass;¼|Ice;|Fighting;½|Poison;|Ground;0|Flying;|Psychic;|Bug;¼|Rock;4|Ghost;|Dragon;|Dark;|Steel;½|Fairy;½
Fire Psychic|Normal;|Fire;½|Water;2|Electric;|Grass;½|Ice;½|Fighting;½|Poison;|Ground;2|Flying;|Psychic;½|Bug;|Rock;2|Ghost;2|Dragon;|Dark;2|Steel;½|Fairy;½
Fire Bug|Normal;|Fire;|Water;2|Electric;|Grass;¼|Ice;½|Fighting;½|Poison;|Ground;|Flying;2|Psychic;|Bug;½|Rock;4|Ghost;|Dragon;|Dark;|Steel;½|Fairy;½
Fire Rock|Normal;½|Fire;¼|Water;4|Electric;|Grass;|Ice;½|Fighting;2|Poison;½|Ground;4|Flying;½|Psychic;|Bug;½|Rock;2|Ghost;|Dragon;|Dark;|Steel;|Fairy;½
Fire Ghost|Normal;0|Fire;½|Water;2|Electric;|Grass;½|Ice;½|Fighting;0|Poison;½|Ground;2|Flying;|Psychic;|Bug;¼|Rock;2|Ghost;2|Dragon;|Dark;2|Steel;½|Fairy;½
Fire Dragon|Normal;|Fire;¼|Water;|Electric;½|Grass;¼|Ice;|Fighting;|Poison;|Ground;2|Flying;|Psychic;|Bug;½|Rock;2|Ghost;|Dragon;2|Dark;|Steel;½|Fairy;
Fire Dark|Normal;|Fire;½|Water;2|Electric;|Grass;½|Ice;½|Fighting;2|Poison;|Ground;2|Flying;|Psychic;0|Bug;|Rock;2|Ghost;½|Dragon;|Dark;½|Steel;½|Fairy;
Fire Steel|Normal;½|Fire;|Water;2|Electric;|Grass;¼|Ice;¼|Fighting;2|Poison;0|Ground;4|Flying;½|Psychic;½|Bug;¼|Rock;|Ghost;|Dragon;½|Dark;|Steel;¼|Fairy;¼
Fire Fairy|Normal;|Fire;½|Water;2|Electric;|Grass;½|Ice;½|Fighting;½|Poison;2|Ground;2|Flying;|Psychic;|Bug;¼|Rock;2|Ghost;|Dragon;0|Dark;½|Steel;|Fairy;½
Water —|Normal;|Fire;½|Water;½|Electric;2|Grass;2|Ice;½|Fighting;|Poison;|Ground;|Flying;|Psychic;|Bug;|Rock;|Ghost;|Dragon;|Dark;|Steel;½|Fairy;
Water Normal|Normal;|Fire;½|Water;½|Electric;2|Grass;2|Ice;½|Fighting;2|Poison;|Ground;|Flying;|Psychic;|Bug;|Rock;|Ghost;0|Dragon;|Dark;|Steel;½|Fairy;
Water Fire|Normal;|Fire;¼|Water;|Electric;2|Grass;|Ice;¼|Fighting;|Poison;|Ground;2|Flying;|Psychic;|Bug;½|Rock;2|Ghost;|Dragon;|Dark;|Steel;¼|Fairy;½
Water Electric|Normal;|Fire;½|Water;½|Electric;|Grass;2|Ice;½|Fighting;|Poison;|Ground;2|Flying;½|Psychic;|Bug;|Rock;|Ghost;|Dragon;|Dark;|Steel;¼|Fairy;
Water Grass|Normal;|Fire;|Water;¼|Electric;|Grass;|Ice;|Fighting;|Poison;2|Ground;½|Flying;2|Psychic;|Bug;2|Rock;|Ghost;|Dragon;|Dark;|Steel;½|Fairy;
Water Ice|Normal;|Fire;|Water;½|Electric;2|Grass;2|Ice;¼|Fighting;2|Poison;|Ground;|Flying;|Psychic;|Bug;|Rock;2|Ghost;|Dragon;|Dark;|Steel;|Fairy;
Water Fighting|Normal;|Fire;½|Water;½|Electric;2|Grass;2|Ice;½|Fighting;|Poison;|Ground;|Flying;2|Psychic;2|Bug;½|Rock;½|Ghost;|Dragon;|Dark;½|Steel;½|Fairy;2
Water Poison|Normal;|Fire;½|Water;½|Electric;2|Grass;|Ice;½|Fighting;½|Poison;½|Ground;2|Flying;|Psychic;2|Bug;½|Rock;|Ghost;|Dragon;|Dark;|Steel;½|Fairy;½
Water Ground|Normal;|Fire;½|Water;|Electric;0|Grass;4|Ice;|Fighting;|Poison;½|Ground;|Flying;|Psychic;|Bug;|Rock;½|Ghost;|Dragon;|Dark;|Steel;½|Fairy;
Water Flying|Normal;|Fire;½|Water;½|Electric;4|Grass;|Ice;|Fighting;½|Poison;|Ground;0|Flying;|Psychic;|Bug;½|Rock;2|Ghost;|Dragon;|Dark;|Steel;½|Fairy;
Water Psychic|Normal;|Fire;½|Water;½|Electric;2|Grass;2|Ice;½|Fighting;½|Poison;|Ground;|Flying;|Psychic;½|Bug;2|Rock;|Ghost;2|Dragon;|Dark;2|Steel;½|Fairy;
Water Bug|Normal;|Fire;|Water;½|Electric;2|Grass;|Ice;½|Fighting;½|Poison;|Ground;½|Flying;2|Psychic;|Bug;|Rock;2|Ghost;|Dragon;|Dark;|Steel;½|Fairy;
Water Rock|Normal;½|Fire;¼|Water;|Electric;2|Grass;4|Ice;½|Fighting;2|Poison;½|Ground;2|Flying;½|Psychic;|Bug;|Rock;|Ghost;|Dragon;|Dark;|Steel;|Fairy;
Water Ghost|Normal;0|Fire;½|Water;½|Electric;2|Grass;2|Ice;½|Fighting;0|Poison;½|Ground;|Flying;|Psychic;|Bug;½|Rock;|Ghost;2|Dragon;|Dark;2|Steel;½|Fairy;
Water Dragon|Normal;|Fire;¼|Water;¼|Electric;|Grass;|Ice;|Fighting;|Poison;|Ground;|Flying;|Psychic;|Bug;|Rock;|Ghost;|Dragon;2|Dark;|Steel;½|Fairy;2
Water Dark|Normal;|Fire;½|Water;½|Electric;2|Grass;2|Ice;½|Fighting;2|Poison;|Ground;|Flying;|Psychic;0|Bug;2|Rock;|Ghost;½|Dragon;|Dark;½|Steel;½|Fairy;2
Water Steel|Normal;½|Fire;|Water;½|Electric;2|Grass;|Ice;¼|Fighting;2|Poison;0|Ground;2|Flying;½|Psychic;½|Bug;½|Rock;½|Ghost;|Dragon;½|Dark;|Steel;¼|Fairy;½
Water Fairy|Normal;|Fire;½|Water;½|Electric;2|Grass;2|Ice;½|Fighting;½|Poison;2|Ground;|Flying;|Psychic;|Bug;½|Rock;|Ghost;|Dragon;0|Dark;½|Steel;|Fairy;
Electric —|Normal;|Fire;|Water;|Electric;½|Grass;|Ice;|Fighting;|Poison;|Ground;2|Flying;½|Psychic;|Bug;|Rock;|Ghost;|Dragon;|Dark;|Steel;½|Fairy;
Electric Normal|Normal;|Fire;|Water;|Electric;½|Grass;|Ice;|Fighting;2|Poison;|Ground;2|Flying;½|Psychic;|Bug;|Rock;|Ghost;0|Dragon;|Dark;|Steel;½|Fairy;
Electric Fire|Normal;|Fire;½|Water;2|Electric;½|Grass;½|Ice;½|Fighting;|Poison;|Ground;4|Flying;½|Psychic;|Bug;½|Rock;2|Ghost;|Dragon;|Dark;|Steel;¼|Fairy;½
Electric Water|Normal;|Fire;½|Water;½|Electric;|Grass;2|Ice;½|Fighting;|Poison;|Ground;2|Flying;½|Psychic;|Bug;|Rock;|Ghost;|Dragon;|Dark;|Steel;¼|Fairy;
Electric Grass|Normal;|Fire;2|Water;½|Electric;¼|Grass;½|Ice;2|Fighting;|Poison;2|Ground;|Flying;|Psychic;|Bug;2|Rock;|Ghost;|Dragon;|Dark;|Steel;½|Fairy;
Electric Ice|Normal;|Fire;2|Water;|Electric;½|Grass;|Ice;½|Fighting;2|Poison;|Ground;2|Flying;½|Psychic;|Bug;|Rock;2|Ghost;|Dragon;|Dark;|Steel;|Fairy;
Electric Fighting|Normal;|Fire;|Water;|Electric;½|Grass;|Ice;|Fighting;|Poison;|Ground;2|Flying;|Psychic;2|Bug;½|Rock;½|Ghost;|Dragon;|Dark;½|Steel;½|Fairy;2
Electric Poison|Normal;|Fire;|Water;|Electric;½|Grass;½|Ice;|Fighting;½|Poison;½|Ground;4|Flying;½|Psychic;2|Bug;½|Rock;|Ghost;|Dragon;|Dark;|Steel;½|Fairy;½
Electric Ground|Normal;|Fire;|Water;2|Electric;0|Grass;2|Ice;2|Fighting;|Poison;½|Ground;2|Flying;½|Psychic;|Bug;|Rock;½|Ghost;|Dragon;|Dark;|Steel;½|Fairy;
Electric Flying|Normal;|Fire;|Water;|Electric;|Grass;½|Ice;2|Fighting;½|Poison;|Ground;0|Flying;½|Psychic;|Bug;½|Rock;2|Ghost;|Dragon;|Dark;|Steel;½|Fairy;
Electric Psychic|Normal;|Fire;|Water;|Electric;½|Grass;|Ice;|Fighting;½|Poison;|Ground;2|Flying;½|Psychic;½|Bug;2|Rock;|Ghost;2|Dragon;|Dark;2|Steel;½|Fairy;
Electric Bug|Normal;|Fire;2|Water;|Electric;½|Grass;½|Ice;|Fighting;½|Poison;|Ground;|Flying;|Psychic;|Bug;|Rock;2|Ghost;|Dragon;|Dark;|Steel;½|Fairy;
Electric Rock|Normal;½|Fire;½|Water;2|Electric;½|Grass;2|Ice;|Fighting;2|Poison;½|Ground;4|Flying;¼|Psychic;|Bug;|Rock;|Ghost;|Dragon;|Dark;|Steel;|Fairy;
Electric Ghost|Normal;0|Fire;|Water;|Electric;½|Grass;|Ice;|Fighting;0|Poison;½|Ground;2|Flying;½|Psychic;|Bug;½|Rock;|Ghost;2|Dragon;|Dark;2|Steel;½|Fairy;
Electric Dragon|Normal;|Fire;½|Water;½|Electric;¼|Grass;½|Ice;2|Fighting;|Poison;|Ground;2|Flying;½|Psychic;|Bug;|Rock;|Ghost;|Dragon;2|Dark;|Steel;½|Fairy;2
Electric Dark|Normal;|Fire;|Water;|Electric;½|Grass;|Ice;|Fighting;2|Poison;|Ground;2|Flying;½|Psychic;0|Bug;2|Rock;|Ghost;½|Dragon;|Dark;½|Steel;½|Fairy;2
Electric Steel|Normal;½|Fire;2|Water;|Electric;½|Grass;½|Ice;½|Fighting;2|Poison;0|Ground;4|Flying;¼|Psychic;½|Bug;½|Rock;½|Ghost;|Dragon;½|Dark;|Steel;¼|Fairy;½
Electric Fairy|Normal;|Fire;|Water;|Electric;½|Grass;|Ice;|Fighting;½|Poison;2|Ground;2|Flying;½|Psychic;|Bug;½|Rock;|Ghost;|Dragon;0|Dark;½|Steel;|Fairy;
Grass —|Normal;|Fire;2|Water;½|Electric;½|Grass;½|Ice;2|Fighting;|Poison;2|Ground;½|Flying;2|Psychic;|Bug;2|Rock;|Ghost;|Dragon;|Dark;|Steel;|Fairy;
Grass Normal|Normal;|Fire;2|Water;½|Electric;½|Grass;½|Ice;2|Fighting;2|Poison;2|Ground;½|Flying;2|Psychic;|Bug;2|Rock;|Ghost;0|Dragon;|Dark;|Steel;|Fairy;
Grass Fire|Normal;|Fire;|Water;|Electric;½|Grass;¼|Ice;|Fighting;|Poison;2|Ground;|Flying;2|Psychic;|Bug;|Rock;2|Ghost;|Dragon;|Dark;|Steel;½|Fairy;½
Grass Water|Normal;|Fire;|Water;¼|Electric;|Grass;|Ice;|Fighting;|Poison;2|Ground;½|Flying;2|Psychic;|Bug;2|Rock;|Ghost;|Dragon;|Dark;|Steel;½|Fairy;
Grass Electric|Normal;|Fire;2|Water;½|Electric;¼|Grass;½|Ice;2|Fighting;|Poison;2|Ground;|Flying;|Psychic;|Bug;2|Rock;|Ghost;|Dragon;|Dark;|Steel;½|Fairy;
Grass Ice|Normal;|Fire;4|Water;½|Electric;½|Grass;½|Ice;|Fighting;2|Poison;2|Ground;½|Flying;2|Psychic;|Bug;2|Rock;2|Ghost;|Dragon;|Dark;|Steel;2|Fairy;
Grass Fighting|Normal;|Fire;2|Water;½|Electric;½|Grass;½|Ice;2|Fighting;|Poison;2|Ground;½|Flying;4|Psychic;2|Bug;|Rock;½|Ghost;|Dragon;|Dark;½|Steel;|Fairy;2
Grass Poison|Normal;|Fire;2|Water;½|Electric;½|Grass;¼|Ice;2|Fighting;½|Poison;|Ground;|Flying;2|Psychic;2|Bug;|Rock;|Ghost;|Dragon;|Dark;|Steel;|Fairy;½
Grass Ground|Normal;|Fire;2|Water;|Electric;0|Grass;|Ice;4|Fighting;|Poison;|Ground;½|Flying;2|Psychic;|Bug;2|Rock;½|Ghost;|Dragon;|Dark;|Steel;|Fairy;
Grass Flying|Normal;|Fire;2|Water;½|Electric;|Grass;¼|Ice;4|Fighting;½|Poison;2|Ground;0|Flying;2|Psychic;|Bug;|Rock;2|Ghost;|Dragon;|Dark;|Steel;|Fairy;
Grass Psychic|Normal;|Fire;2|Water;½|Electric;½|Grass;½|Ice;2|Fighting;½|Poison;2|Ground;½|Flying;2|Psychic;½|Bug;4|Rock;|Ghost;2|Dragon;|Dark;2|Steel;|Fairy;
Grass Bug|Normal;|Fire;4|Water;½|Electric;½|Grass;¼|Ice;2|Fighting;½|Poison;2|Ground;¼|Flying;4|Psychic;|Bug;2|Rock;2|Ghost;|Dragon;|Dark;|Steel;|Fairy;
Grass Rock|Normal;½|Fire;|Water;|Electric;½|Grass;|Ice;2|Fighting;2|Poison;|Ground;|Flying;|Psychic;|Bug;2|Rock;|Ghost;|Dragon;|Dark;|Steel;2|Fairy;
Grass Ghost|Normal;0|Fire;2|Water;½|Electric;½|Grass;½|Ice;2|Fighting;0|Poison;|Ground;½|Flying;2|Psychic;|Bug;|Rock;|Ghost;2|Dragon;|Dark;2|Steel;|Fairy;
Grass Dragon|Normal;|Fire;|Water;¼|Electric;¼|Grass;¼|Ice;4|Fighting;|Poison;2|Ground;½|Flying;2|Psychic;|Bug;2|Rock;|Ghost;|Dragon;2|Dark;|Steel;|Fairy;2
Grass Dark|Normal;|Fire;2|Water;½|Electric;½|Grass;½|Ice;2|Fighting;2|Poison;2|Ground;½|Flying;2|Psychic;0|Bug;4|Rock;|Ghost;½|Dragon;|Dark;½|Steel;|Fairy;2
Grass Steel|Normal;½|Fire;4|Water;½|Electric;½|Grass;¼|Ice;|Fighting;2|Poison;0|Ground;|Flying;|Psychic;½|Bug;|Rock;½|Ghost;|Dragon;½|Dark;|Steel;½|Fairy;½
Grass Fairy|Normal;|Fire;2|Water;½|Electric;½|Grass;½|Ice;2|Fighting;½|Poison;4|Ground;½|Flying;2|Psychic;|Bug;|Rock;|Ghost;|Dragon;0|Dark;½|Steel;2|Fairy;
Ice —|Normal;|Fire;2|Water;|Electric;|Grass;|Ice;½|Fighting;2|Poison;|Ground;|Flying;|Psychic;|Bug;|Rock;2|Ghost;|Dragon;|Dark;|Steel;2|Fairy;
Ice Normal|Normal;|Fire;2|Water;|Electric;|Grass;|Ice;½|Fighting;4|Poison;|Ground;|Flying;|Psychic;|Bug;|Rock;2|Ghost;0|Dragon;|Dark;|Steel;2|Fairy;
Ice Fire|Normal;|Fire;|Water;2|Electric;|Grass;½|Ice;¼|Fighting;2|Poison;|Ground;2|Flying;|Psychic;|Bug;½|Rock;4|Ghost;|Dragon;|Dark;|Steel;|Fairy;½
Ice Water|Normal;|Fire;|Water;½|Electric;2|Grass;2|Ice;¼|Fighting;2|Poison;|Ground;|Flying;|Psychic;|Bug;|Rock;2|Ghost;|Dragon;|Dark;|Steel;|Fairy;
Ice Electric|Normal;|Fire;2|Water;|Electric;½|Grass;|Ice;½|Fighting;2|Poison;|Ground;2|Flying;½|Psychic;|Bug;|Rock;2|Ghost;|Dragon;|Dark;|Steel;|Fairy;
Ice Grass|Normal;|Fire;4|Water;½|Electric;½|Grass;½|Ice;|Fighting;2|Poison;2|Ground;½|Flying;2|Psychic;|Bug;2|Rock;2|Ghost;|Dragon;|Dark;|Steel;2|Fairy;
Ice Fighting|Normal;|Fire;2|Water;|Electric;|Grass;|Ice;½|Fighting;2|Poison;|Ground;|Flying;2|Psychic;2|Bug;½|Rock;|Ghost;|Dragon;|Dark;½|Steel;2|Fairy;2
Ice Poison|Normal;|Fire;2|Water;|Electric;|Grass;½|Ice;½|Fighting;|Poison;½|Ground;2|Flying;|Psychic;2|Bug;½|Rock;2|Ghost;|Dragon;|Dark;|Steel;2|Fairy;½
Ice Ground|Normal;|Fire;2|Water;2|Electric;0|Grass;2|Ice;|Fighting;2|Poison;½|Ground;|Flying;|Psychic;|Bug;|Rock;|Ghost;|Dragon;|Dark;|Steel;2|Fairy;
Ice Flying|Normal;|Fire;2|Water;|Electric;2|Grass;½|Ice;|Fighting;|Poison;|Ground;0|Flying;|Psychic;|Bug;½|Rock;4|Ghost;|Dragon;|Dark;|Steel;2|Fairy;
Ice Psychic|Normal;|Fire;2|Water;|Electric;|Grass;|Ice;½|Fighting;|Poison;|Ground;|Flying;|Psychic;½|Bug;2|Rock;2|Ghost;2|Dragon;|Dark;2|Steel;2|Fairy;
Ice Bug|Normal;|Fire;4|Water;|Electric;|Grass;½|Ice;½|Fighting;|Poison;|Ground;½|Flying;2|Psychic;|Bug;|Rock;4|Ghost;|Dragon;|Dark;|Steel;2|Fairy;
Ice Rock|Normal;½|Fire;|Water;2|Electric;|Grass;2|Ice;½|Fighting;4|Poison;½|Ground;2|Flying;½|Psychic;|Bug;|Rock;2|Ghost;|Dragon;|Dark;|Steel;4|Fairy;
Ice Ghost|Normal;0|Fire;2|Water;|Electric;|Grass;|Ice;½|Fighting;0|Poison;½|Ground;|Flying;|Psychic;|Bug;½|Rock;2|Ghost;2|Dragon;|Dark;2|Steel;2|Fairy;
Ice Dragon|Normal;|Fire;|Water;½|Electric;½|Grass;½|Ice;|Fighting;2|Poison;|Ground;|Flying;|Psychic;|Bug;|Rock;2|Ghost;|Dragon;2|Dark;|Steel;2|Fairy;2
Ice Dark|Normal;|Fire;2|Water;|Electric;|Grass;|Ice;½|Fighting;4|Poison;|Ground;|Flying;|Psychic;0|Bug;2|Rock;2|Ghost;½|Dragon;|Dark;½|Steel;2|Fairy;2
Ice Steel|Normal;½|Fire;4|Water;|Electric;|Grass;½|Ice;¼|Fighting;4|Poison;0|Ground;2|Flying;½|Psychic;½|Bug;½|Rock;|Ghost;|Dragon;½|Dark;|Steel;|Fairy;½
Ice Fairy|Normal;|Fire;2|Water;|Electric;|Grass;|Ice;½|Fighting;|Poison;2|Ground;|Flying;|Psychic;|Bug;½|Rock;2|Ghost;|Dragon;0|Dark;½|Steel;4|Fairy;
Fighting —|Normal;|Fire;|Water;|Electric;|Grass;|Ice;|Fighting;|Poison;|Ground;|Flying;2|Psychic;2|Bug;½|Rock;½|Ghost;|Dragon;|Dark;½|Steel;|Fairy;2
Fighting Normal|Normal;|Fire;|Water;|Electric;|Grass;|Ice;|Fighting;2|Poison;|Ground;|Flying;2|Psychic;2|Bug;½|Rock;½|Ghost;0|Dragon;|Dark;½|Steel;|Fairy;2
Fighting Fire|Normal;|Fire;½|Water;2|Electric;|Grass;½|Ice;½|Fighting;|Poison;|Ground;2|Flying;2|Psychic;2|Bug;¼|Rock;|Ghost;|Dragon;|Dark;½|Steel;½|Fairy;
Fighting Water|Normal;|Fire;½|Water;½|Electric;2|Grass;2|Ice;½|Fighting;|Poison;|Ground;|Flying;2|Psychic;2|Bug;½|Rock;½|Ghost;|Dragon;|Dark;½|Steel;½|Fairy;2
Fighting Electric|Normal;|Fire;|Water;|Electric;½|Grass;|Ice;|Fighting;|Poison;|Ground;2|Flying;|Psychic;2|Bug;½|Rock;½|Ghost;|Dragon;|Dark;½|Steel;½|Fairy;2
Fighting Grass|Normal;|Fire;2|Water;½|Electric;½|Grass;½|Ice;2|Fighting;|Poison;2|Ground;½|Flying;4|Psychic;2|Bug;|Rock;½|Ghost;|Dragon;|Dark;½|Steel;|Fairy;2
Fighting Ice|Normal;|Fire;2|Water;|Electric;|Grass;|Ice;½|Fighting;2|Poison;|Ground;|Flying;2|Psychic;2|Bug;½|Rock;|Ghost;|Dragon;|Dark;½|Steel;2|Fairy;2
Fighting Poison|Normal;|Fire;|Water;|Electric;|Grass;½|Ice;|Fighting;½|Poison;½|Ground;2|Flying;2|Psychic;4|Bug;¼|Rock;½|Ghost;|Dragon;|Dark;½|Steel;|Fairy;
Fighting Ground|Normal;|Fire;|Water;2|Electric;0|Grass;2|Ice;2|Fighting;|Poison;½|Ground;|Flying;2|Psychic;2|Bug;½|Rock;¼|Ghost;|Dragon;|Dark;½|Steel;|Fairy;2
Fighting Flying|Normal;|Fire;|Water;|Electric;2|Grass;½|Ice;2|Fighting;½|Poison;|Ground;0|Flying;2|Psychic;2|Bug;¼|Rock;|Ghost;|Dragon;|Dark;½|Steel;|Fairy;2
Fighting Psychic|Normal;|Fire;|Water;|Electric;|Grass;|Ice;|Fighting;½|Poison;|Ground;|Flying;2|Psychic;|Bug;|Rock;½|Ghost;2|Dragon;|Dark;|Steel;|Fairy;2
Fighting Bug|Normal;|Fire;2|Water;|Electric;|Grass;½|Ice;|Fighting;½|Poison;|Ground;½|Flying;4|Psychic;2|Bug;½|Rock;|Ghost;|Dragon;|Dark;½|Steel;|Fairy;2
Fighting Rock|Normal;½|Fire;½|Water;2|Electric;|Grass;2|Ice;|Fighting;2|Poison;½|Ground;2|Flying;|Psychic;2|Bug;½|Rock;½|Ghost;|Dragon;|Dark;½|Steel;2|Fairy;2
Fighting Ghost|Normal;0|Fire;|Water;|Electric;|Grass;|Ice;|Fighting;0|Poison;½|Ground;|Flying;2|Psychic;2|Bug;¼|Rock;½|Ghost;2|Dragon;|Dark;|Steel;|Fairy;2
Fighting Dragon|Normal;|Fire;½|Water;½|Electric;½|Grass;½|Ice;2|Fighting;|Poison;|Ground;|Flying;2|Psychic;2|Bug;½|Rock;½|Ghost;|Dragon;2|Dark;½|Steel;|Fairy;4
Fighting Dark|Normal;|Fire;|Water;|Electric;|Grass;|Ice;|Fighting;2|Poison;|Ground;|Flying;2|Psychic;0|Bug;|Rock;½|Ghost;½|Dragon;|Dark;¼|Steel;|Fairy;4
Fighting Steel|Normal;½|Fire;2|Water;|Electric;|Grass;½|Ice;½|Fighting;2|Poison;0|Ground;2|Flying;|Psychic;|Bug;¼|Rock;¼|Ghost;|Dragon;½|Dark;½|Steel;½|Fairy;
Fighting Fairy|Normal;|Fire;|Water;|Electric;|Grass;|Ice;|Fighting;½|Poison;2|Ground;|Flying;2|Psychic;2|Bug;¼|Rock;½|Ghost;|Dragon;0|Dark;¼|Steel;2|Fairy;2
Poison —|Normal;|Fire;|Water;|Electric;|Grass;½|Ice;|Fighting;½|Poison;½|Ground;2|Flying;|Psychic;2|Bug;½|Rock;|Ghost;|Dragon;|Dark;|Steel;|Fairy;½
Poison Normal|Normal;|Fire;|Water;|Electric;|Grass;½|Ice;|Fighting;|Poison;½|Ground;2|Flying;|Psychic;2|Bug;½|Rock;|Ghost;0|Dragon;|Dark;|Steel;|Fairy;½
Poison Fire|Normal;|Fire;½|Water;2|Electric;|Grass;¼|Ice;½|Fighting;½|Poison;½|Ground;4|Flying;|Psychic;2|Bug;¼|Rock;2|Ghost;|Dragon;|Dark;|Steel;½|Fairy;¼
Poison Water|Normal;|Fire;½|Water;½|Electric;2|Grass;|Ice;½|Fighting;½|Poison;½|Ground;2|Flying;|Psychic;2|Bug;½|Rock;|Ghost;|Dragon;|Dark;|Steel;½|Fairy;½
Poison Electric|Normal;|Fire;|Water;|Electric;½|Grass;½|Ice;|Fighting;½|Poison;½|Ground;4|Flying;½|Psychic;2|Bug;½|Rock;|Ghost;|Dragon;|Dark;|Steel;½|Fairy;½
Poison Grass|Normal;|Fire;2|Water;½|Electric;½|Grass;¼|Ice;2|Fighting;½|Poison;|Ground;|Flying;2|Psychic;2|Bug;|Rock;|Ghost;|Dragon;|Dark;|Steel;|Fairy;½
Poison Ice|Normal;|Fire;2|Water;|Electric;|Grass;½|Ice;½|Fighting;|Poison;½|Ground;2|Flying;|Psychic;2|Bug;½|Rock;2|Ghost;|Dragon;|Dark;|Steel;2|Fairy;½
Poison Fighting|Normal;|Fire;|Water;|Electric;|Grass;½|Ice;|Fighting;½|Poison;½|Ground;2|Flying;2|Psychic;4|Bug;¼|Rock;½|Ghost;|Dragon;|Dark;½|Steel;|Fairy;
Poison Ground|Normal;|Fire;|Water;2|Electric;0|Grass;|Ice;2|Fighting;½|Poison;¼|Ground;2|Flying;|Psychic;2|Bug;½|Rock;½|Ghost;|Dragon;|Dark;|Steel;|Fairy;½
Poison Flying|Normal;|Fire;|Water;|Electric;2|Grass;¼|Ice;2|Fighting;¼|Poison;½|Ground;0|Flying;|Psychic;2|Bug;¼|Rock;2|Ghost;|Dragon;|Dark;|Steel;|Fairy;½
Poison Psychic|Normal;|Fire;|Water;|Electric;|Grass;½|Ice;|Fighting;¼|Poison;½|Ground;2|Flying;|Psychic;|Bug;|Rock;|Ghost;2|Dragon;|Dark;2|Steel;|Fairy;½
Poison Bug|Normal;|Fire;2|Water;|Electric;|Grass;¼|Ice;|Fighting;¼|Poison;½|Ground;|Flying;2|Psychic;2|Bug;½|Rock;2|Ghost;|Dragon;|Dark;|Steel;|Fairy;½
Poison Rock|Normal;½|Fire;½|Water;2|Electric;|Grass;|Ice;|Fighting;|Poison;¼|Ground;4|Flying;½|Psychic;2|Bug;½|Rock;|Ghost;|Dragon;|Dark;|Steel;2|Fairy;½
Poison Ghost|Normal;0|Fire;|Water;|Electric;|Grass;½|Ice;|Fighting;0|Poison;¼|Ground;2|Flying;|Psychic;2|Bug;¼|Rock;|Ghost;2|Dragon;|Dark;2|Steel;|Fairy;½
Poison Dragon|Normal;|Fire;½|Water;½|Electric;½|Grass;¼|Ice;2|Fighting;½|Poison;½|Ground;2|Flying;|Psychic;2|Bug;½|Rock;|Ghost;|Dragon;2|Dark;|Steel;|Fairy;
Poison Dark|Normal;|Fire;|Water;|Electric;|Grass;½|Ice;|Fighting;|Poison;½|Ground;2|Flying;|Psychic;0|Bug;|Rock;|Ghost;½|Dragon;|Dark;½|Steel;|Fairy;
Poison Steel|Normal;½|Fire;2|Water;|Electric;|Grass;¼|Ice;½|Fighting;|Poison;0|Ground;4|Flying;½|Psychic;|Bug;¼|Rock;½|Ghost;|Dragon;½|Dark;|Steel;½|Fairy;¼
Poison Fairy|Normal;|Fire;|Water;|Electric;|Grass;½|Ice;|Fighting;¼|Poison;|Ground;2|Flying;|Psychic;2|Bug;¼|Rock;|Ghost;|Dragon;0|Dark;½|Steel;2|Fairy;½
Ground —|Normal;|Fire;|Water;2|Electric;0|Grass;2|Ice;2|Fighting;|Poison;½|Ground;|Flying;|Psychic;|Bug;|Rock;½|Ghost;|Dragon;|Dark;|Steel;|Fairy;
Ground Normal|Normal;|Fire;|Water;2|Electric;0|Grass;2|Ice;2|Fighting;2|Poison;½|Ground;|Flying;|Psychic;|Bug;|Rock;½|Ghost;0|Dragon;|Dark;|Steel;|Fairy;
Ground Fire|Normal;|Fire;½|Water;4|Electric;0|Grass;|Ice;|Fighting;|Poison;½|Ground;2|Flying;|Psychic;|Bug;½|Rock;|Ghost;|Dragon;|Dark;|Steel;½|Fairy;½
Ground Water|Normal;|Fire;½|Water;|Electric;0|Grass;4|Ice;|Fighting;|Poison;½|Ground;|Flying;|Psychic;|Bug;|Rock;½|Ghost;|Dragon;|Dark;|Steel;½|Fairy;
Ground Electric|Normal;|Fire;|Water;2|Electric;0|Grass;2|Ice;2|Fighting;|Poison;½|Ground;2|Flying;½|Psychic;|Bug;|Rock;½|Ghost;|Dragon;|Dark;|Steel;½|Fairy;
Ground Grass|Normal;|Fire;2|Water;|Electric;0|Grass;|Ice;4|Fighting;|Poison;|Ground;½|Flying;2|Psychic;|Bug;2|Rock;½|Ghost;|Dragon;|Dark;|Steel;|Fairy;
Ground Ice|Normal;|Fire;2|Water;2|Electric;0|Grass;2|Ice;|Fighting;2|Poison;½|Ground;|Flying;|Psychic;|Bug;|Rock;|Ghost;|Dragon;|Dark;|Steel;2|Fairy;
Ground Fighting|Normal;|Fire;|Water;2|Electric;0|Grass;2|Ice;2|Fighting;|Poison;½|Ground;|Flying;2|Psychic;2|Bug;½|Rock;¼|Ghost;|Dragon;|Dark;½|Steel;|Fairy;2
Ground Poison|Normal;|Fire;|Water;2|Electric;0|Grass;|Ice;2|Fighting;½|Poison;¼|Ground;2|Flying;|Psychic;2|Bug;½|Rock;½|Ghost;|Dragon;|Dark;|Steel;|Fairy;½
Ground Flying|Normal;|Fire;|Water;2|Electric;0|Grass;|Ice;4|Fighting;½|Poison;½|Ground;0|Flying;|Psychic;|Bug;½|Rock;|Ghost;|Dragon;|Dark;|Steel;|Fairy;
Ground Psychic|Normal;|Fire;|Water;2|Electric;0|Grass;2|Ice;2|Fighting;½|Poison;½|Ground;|Flying;|Psychic;½|Bug;2|Rock;½|Ghost;2|Dragon;|Dark;2|Steel;|Fairy;
Ground Bug|Normal;|Fire;2|Water;2|Electric;0|Grass;|Ice;2|Fighting;½|Poison;½|Ground;½|Flying;2|Psychic;|Bug;|Rock;|Ghost;|Dragon;|Dark;|Steel;|Fairy;
Ground Rock|Normal;½|Fire;½|Water;4|Electric;0|Grass;4|Ice;2|Fighting;2|Poison;¼|Ground;2|Flying;½|Psychic;|Bug;|Rock;½|Ghost;|Dragon;|Dark;|Steel;2|Fairy;
Ground Ghost|Normal;0|Fire;|Water;2|Electric;0|Grass;2|Ice;2|Fighting;0|Poison;¼|Ground;|Flying;|Psychic;|Bug;½|Rock;½|Ghost;2|Dragon;|Dark;2|Steel;|Fairy;
Ground Dragon|Normal;|Fire;½|Water;|Electric;0|Grass;|Ice;4|Fighting;|Poison;½|Ground;|Flying;|Psychic;|Bug;|Rock;½|Ghost;|Dragon;2|Dark;|Steel;|Fairy;2
Ground Dark|Normal;|Fire;|Water;2|Electric;0|Grass;2|Ice;2|Fighting;2|Poison;½|Ground;|Flying;|Psychic;0|Bug;2|Rock;½|Ghost;½|Dragon;|Dark;½|Steel;|Fairy;2
Ground Steel|Normal;½|Fire;2|Water;2|Electric;0|Grass;|Ice;|Fighting;2|Poison;0|Ground;2|Flying;½|Psychic;½|Bug;½|Rock;¼|Ghost;|Dragon;½|Dark;|Steel;½|Fairy;½
Ground Fairy|Normal;|Fire;|Water;2|Electric;0|Grass;2|Ice;2|Fighting;½|Poison;|Ground;|Flying;|Psychic;|Bug;½|Rock;½|Ghost;|Dragon;0|Dark;½|Steel;2|Fairy;
Flying —|Normal;|Fire;|Water;|Electric;2|Grass;½|Ice;2|Fighting;½|Poison;|Ground;0|Flying;|Psychic;|Bug;½|Rock;2|Ghost;|Dragon;|Dark;|Steel;|Fairy;
Flying Normal|Normal;|Fire;|Water;|Electric;2|Grass;½|Ice;2|Fighting;|Poison;|Ground;0|Flying;|Psychic;|Bug;½|Rock;2|Ghost;0|Dragon;|Dark;|Steel;|Fairy;
Flying Fire|Normal;|Fire;½|Water;2|Electric;2|Grass;¼|Ice;|Fighting;½|Poison;|Ground;0|Flying;|Psychic;|Bug;¼|Rock;4|Ghost;|Dragon;|Dark;|Steel;½|Fairy;½
Flying Water|Normal;|Fire;½|Water;½|Electric;4|Grass;|Ice;|Fighting;½|Poison;|Ground;0|Flying;|Psychic;|Bug;½|Rock;2|Ghost;|Dragon;|Dark;|Steel;½|Fairy;
Flying Electric|Normal;|Fire;|Water;|Electric;|Grass;½|Ice;2|Fighting;½|Poison;|Ground;0|Flying;½|Psychic;|Bug;½|Rock;2|Ghost;|Dragon;|Dark;|Steel;½|Fairy;
Flying Grass|Normal;|Fire;2|Water;½|Electric;|Grass;¼|Ice;4|Fighting;½|Poison;2|Ground;0|Flying;2|Psychic;|Bug;|Rock;2|Ghost;|Dragon;|Dark;|Steel;|Fairy;
Flying Ice|Normal;|Fire;2|Water;|Electric;2|Grass;½|Ice;|Fighting;|Poison;|Ground;0|Flying;|Psychic;|Bug;½|Rock;4|Ghost;|Dragon;|Dark;|Steel;2|Fairy;
Flying Fighting|Normal;|Fire;|Water;|Electric;2|Grass;½|Ice;2|Fighting;½|Poison;|Ground;0|Flying;2|Psychic;2|Bug;¼|Rock;|Ghost;|Dragon;|Dark;½|Steel;|Fairy;2
Flying Poison|Normal;|Fire;|Water;|Electric;2|Grass;¼|Ice;2|Fighting;¼|Poison;½|Ground;0|Flying;|Psychic;2|Bug;¼|Rock;2|Ghost;|Dragon;|Dark;|Steel;|Fairy;½
Flying Ground|Normal;|Fire;|Water;2|Electric;0|Grass;|Ice;4|Fighting;½|Poison;½|Ground;0|Flying;|Psychic;|Bug;½|Rock;|Ghost;|Dragon;|Dark;|Steel;|Fairy;
Flying Psychic|Normal;|Fire;|Water;|Electric;2|Grass;½|Ice;2|Fighting;¼|Poison;|Ground;0|Flying;|Psychic;½|Bug;|Rock;2|Ghost;2|Dragon;|Dark;2|Steel;|Fairy;
Flying Bug|Normal;|Fire;2|Water;|Electric;2|Grass;¼|Ice;2|Fighting;¼|Poison;|Ground;0|Flying;2|Psychic;|Bug;½|Rock;4|Ghost;|Dragon;|Dark;|Steel;|Fairy;
Flying Rock|Normal;½|Fire;½|Water;2|Electric;2|Grass;|Ice;2|Fighting;|Poison;½|Ground;0|Flying;½|Psychic;|Bug;½|Rock;2|Ghost;|Dragon;|Dark;|Steel;2|Fairy;
Flying Ghost|Normal;0|Fire;|Water;|Electric;2|Grass;½|Ice;2|Fighting;0|Poison;½|Ground;0|Flying;|Psychic;|Bug;¼|Rock;2|Ghost;2|Dragon;|Dark;2|Steel;|Fairy;
Flying Dragon|Normal;|Fire;½|Water;½|Electric;|Grass;¼|Ice;4|Fighting;½|Poison;|Ground;0|Flying;|Psychic;|Bug;½|Rock;2|Ghost;|Dragon;2|Dark;|Steel;|Fairy;2
Flying Dark|Normal;|Fire;|Water;|Electric;2|Grass;½|Ice;2|Fighting;|Poison;|Ground;0|Flying;|Psychic;0|Bug;|Rock;2|Ghost;½|Dragon;|Dark;½|Steel;|Fairy;2
Flying Steel|Normal;½|Fire;2|Water;|Electric;2|Grass;¼|Ice;|Fighting;|Poison;0|Ground;0|Flying;½|Psychic;½|Bug;¼|Rock;|Ghost;|Dragon;½|Dark;|Steel;½|Fairy;½
Flying Fairy|Normal;|Fire;|Water;|Electric;2|Grass;½|Ice;2|Fighting;¼|Poison;2|Ground;0|Flying;|Psychic;|Bug;¼|Rock;2|Ghost;|Dragon;0|Dark;½|Steel;2|Fairy;
Psychic —|Normal;|Fire;|Water;|Electric;|Grass;|Ice;|Fighting;½|Poison;|Ground;|Flying;|Psychic;½|Bug;2|Rock;|Ghost;2|Dragon;|Dark;2|Steel;|Fairy;
Psychic Normal|Normal;|Fire;|Water;|Electric;|Grass;|Ice;|Fighting;|Poison;|Ground;|Flying;|Psychic;½|Bug;2|Rock;|Ghost;0|Dragon;|Dark;2|Steel;|Fairy;
Psychic Fire|Normal;|Fire;½|Water;2|Electric;|Grass;½|Ice;½|Fighting;½|Poison;|Ground;2|Flying;|Psychic;½|Bug;|Rock;2|Ghost;2|Dragon;|Dark;2|Steel;½|Fairy;½
Psychic Water|Normal;|Fire;½|Water;½|Electric;2|Grass;2|Ice;½|Fighting;½|Poison;|Ground;|Flying;|Psychic;½|Bug;2|Rock;|Ghost;2|Dragon;|Dark;2|Steel;½|Fairy;
Psychic Electric|Normal;|Fire;|Water;|Electric;½|Grass;|Ice;|Fighting;½|Poison;|Ground;2|Flying;½|Psychic;½|Bug;2|Rock;|Ghost;2|Dragon;|Dark;2|Steel;½|Fairy;
Psychic Grass|Normal;|Fire;2|Water;½|Electric;½|Grass;½|Ice;2|Fighting;½|Poison;2|Ground;½|Flying;2|Psychic;½|Bug;4|Rock;|Ghost;2|Dragon;|Dark;2|Steel;|Fairy;
Psychic Ice|Normal;|Fire;2|Water;|Electric;|Grass;|Ice;½|Fighting;|Poison;|Ground;|Flying;|Psychic;½|Bug;2|Rock;2|Ghost;2|Dragon;|Dark;2|Steel;2|Fairy;
Psychic Fighting|Normal;|Fire;|Water;|Electric;|Grass;|Ice;|Fighting;½|Poison;|Ground;|Flying;2|Psychic;|Bug;|Rock;½|Ghost;2|Dragon;|Dark;|Steel;|Fairy;2
Psychic Poison|Normal;|Fire;|Water;|Electric;|Grass;½|Ice;|Fighting;¼|Poison;½|Ground;2|Flying;|Psychic;|Bug;|Rock;|Ghost;2|Dragon;|Dark;2|Steel;|Fairy;½
Psychic Ground|Normal;|Fire;|Water;2|Electric;0|Grass;2|Ice;2|Fighting;½|Poison;½|Ground;|Flying;|Psychic;½|Bug;2|Rock;½|Ghost;2|Dragon;|Dark;2|Steel;|Fairy;
Psychic Flying|Normal;|Fire;|Water;|Electric;2|Grass;½|Ice;2|Fighting;¼|Poison;|Ground;0|Flying;|Psychic;½|Bug;|Rock;2|Ghost;2|Dragon;|Dark;2|Steel;|Fairy;
Psychic Bug|Normal;|Fire;2|Water;|Electric;|Grass;½|Ice;|Fighting;¼|Poison;|Ground;½|Flying;2|Psychic;½|Bug;2|Rock;2|Ghost;2|Dragon;|Dark;2|Steel;|Fairy;
Psychic Rock|Normal;½|Fire;½|Water;2|Electric;|Grass;2|Ice;|Fighting;|Poison;½|Ground;2|Flying;½|Psychic;½|Bug;2|Rock;|Ghost;2|Dragon;|Dark;2|Steel;2|Fairy;
Psychic Ghost|Normal;0|Fire;|Water;|Electric;|Grass;|Ice;|Fighting;0|Poison;½|Ground;|Flying;|Psychic;½|Bug;|Rock;|Ghost;4|Dragon;|Dark;4|Steel;|Fairy;
Psychic Dragon|Normal;|Fire;½|Water;½|Electric;½|Grass;½|Ice;2|Fighting;½|Poison;|Ground;|Flying;|Psychic;½|Bug;2|Rock;|Ghost;2|Dragon;2|Dark;2|Steel;|Fairy;2
Psychic Dark|Normal;|Fire;|Water;|Electric;|Grass;|Ice;|Fighting;|Poison;|Ground;|Flying;|Psychic;0|Bug;4|Rock;|Ghost;|Dragon;|Dark;|Steel;|Fairy;2
Psychic Steel|Normal;½|Fire;2|Water;|Electric;|Grass;½|Ice;½|Fighting;|Poison;0|Ground;2|Flying;½|Psychic;¼|Bug;|Rock;½|Ghost;2|Dragon;½|Dark;2|Steel;½|Fairy;½
Psychic Fairy|Normal;|Fire;|Water;|Electric;|Grass;|Ice;|Fighting;¼|Poison;2|Ground;|Flying;|Psychic;½|Bug;|Rock;|Ghost;2|Dragon;0|Dark;|Steel;2|Fairy;
Bug —|Normal;|Fire;2|Water;|Electric;|Grass;½|Ice;|Fighting;½|Poison;|Ground;½|Flying;2|Psychic;|Bug;|Rock;2|Ghost;|Dragon;|Dark;|Steel;|Fairy;
Bug Normal|Normal;|Fire;2|Water;|Electric;|Grass;½|Ice;|Fighting;|Poison;|Ground;½|Flying;2|Psychic;|Bug;|Rock;2|Ghost;0|Dragon;|Dark;|Steel;|Fairy;
Bug Fire|Normal;|Fire;|Water;2|Electric;|Grass;¼|Ice;½|Fighting;½|Poison;|Ground;|Flying;2|Psychic;|Bug;½|Rock;4|Ghost;|Dragon;|Dark;|Steel;½|Fairy;½
Bug Water|Normal;|Fire;|Water;½|Electric;2|Grass;|Ice;½|Fighting;½|Poison;|Ground;½|Flying;2|Psychic;|Bug;|Rock;2|Ghost;|Dragon;|Dark;|Steel;½|Fairy;
Bug Electric|Normal;|Fire;2|Water;|Electric;½|Grass;½|Ice;|Fighting;½|Poison;|Ground;|Flying;|Psychic;|Bug;|Rock;2|Ghost;|Dragon;|Dark;|Steel;½|Fairy;
Bug Grass|Normal;|Fire;4|Water;½|Electric;½|Grass;¼|Ice;2|Fighting;½|Poison;2|Ground;¼|Flying;4|Psychic;|Bug;2|Rock;2|Ghost;|Dragon;|Dark;|Steel;|Fairy;
Bug Ice|Normal;|Fire;4|Water;|Electric;|Grass;½|Ice;½|Fighting;|Poison;|Ground;½|Flying;2|Psychic;|Bug;|Rock;4|Ghost;|Dragon;|Dark;|Steel;2|Fairy;
Bug Fighting|Normal;|Fire;2|Water;|Electric;|Grass;½|Ice;|Fighting;½|Poison;|Ground;½|Flying;4|Psychic;2|Bug;½|Rock;|Ghost;|Dragon;|Dark;½|Steel;|Fairy;2
Bug Poison|Normal;|Fire;2|Water;|Electric;|Grass;¼|Ice;|Fighting;¼|Poison;½|Ground;|Flying;2|Psychic;2|Bug;½|Rock;2|Ghost;|Dragon;|Dark;|Steel;|Fairy;½
Bug Ground|Normal;|Fire;2|Water;2|Electric;0|Grass;|Ice;2|Fighting;½|Poison;½|Ground;½|Flying;2|Psychic;|Bug;|Rock;|Ghost;|Dragon;|Dark;|Steel;|Fairy;
Bug Flying|Normal;|Fire;2|Water;|Electric;2|Grass;¼|Ice;2|Fighting;¼|Poison;|Ground;0|Flying;2|Psychic;|Bug;½|Rock;4|Ghost;|Dragon;|Dark;|Steel;|Fairy;
Bug Psychic|Normal;|Fire;2|Water;|Electric;|Grass;½|Ice;|Fighting;¼|Poison;|Ground;½|Flying;2|Psychic;½|Bug;2|Rock;2|Ghost;2|Dragon;|Dark;2|Steel;|Fairy;
Bug Rock|Normal;½|Fire;|Water;2|Electric;|Grass;|Ice;|Fighting;|Poison;½|Ground;|Flying;|Psychic;|Bug;|Rock;2|Ghost;|Dragon;|Dark;|Steel;2|Fairy;
Bug Ghost|Normal;0|Fire;2|Water;|Electric;|Grass;½|Ice;|Fighting;0|Poison;½|Ground;½|Flying;2|Psychic;|Bug;½|Rock;2|Ghost;2|Dragon;|Dark;2|Steel;|Fairy;
Bug Dragon|Normal;|Fire;|Water;½|Electric;½|Grass;¼|Ice;2|Fighting;½|Poison;|Ground;½|Flying;2|Psychic;|Bug;|Rock;2|Ghost;|Dragon;2|Dark;|Steel;|Fairy;2
Bug Dark|Normal;|Fire;2|Water;|Electric;|Grass;½|Ice;|Fighting;|Poison;|Ground;½|Flying;2|Psychic;0|Bug;2|Rock;2|Ghost;½|Dragon;|Dark;½|Steel;|Fairy;2
Bug Steel|Normal;½|Fire;4|Water;|Electric;|Grass;¼|Ice;½|Fighting;|Poison;0|Ground;|Flying;|Psychic;½|Bug;½|Rock;|Ghost;|Dragon;½|Dark;|Steel;½|Fairy;½
Bug Fairy|Normal;|Fire;2|Water;|Electric;|Grass;½|Ice;|Fighting;¼|Poison;2|Ground;½|Flying;2|Psychic;|Bug;½|Rock;2|Ghost;|Dragon;0|Dark;½|Steel;2|Fairy;
Rock —|Normal;½|Fire;½|Water;2|Electric;|Grass;2|Ice;|Fighting;2|Poison;½|Ground;2|Flying;½|Psychic;|Bug;|Rock;|Ghost;|Dragon;|Dark;|Steel;2|Fairy;
Rock Normal|Normal;½|Fire;½|Water;2|Electric;|Grass;2|Ice;|Fighting;4|Poison;½|Ground;2|Flying;½|Psychic;|Bug;|Rock;|Ghost;0|Dragon;|Dark;|Steel;2|Fairy;
Rock Fire|Normal;½|Fire;¼|Water;4|Electric;|Grass;|Ice;½|Fighting;2|Poison;½|Ground;4|Flying;½|Psychic;|Bug;½|Rock;2|Ghost;|Dragon;|Dark;|Steel;|Fairy;½
Rock Water|Normal;½|Fire;¼|Water;|Electric;2|Grass;4|Ice;½|Fighting;2|Poison;½|Ground;2|Flying;½|Psychic;|Bug;|Rock;|Ghost;|Dragon;|Dark;|Steel;|Fairy;
Rock Electric|Normal;½|Fire;½|Water;2|Electric;½|Grass;2|Ice;|Fighting;2|Poison;½|Ground;4|Flying;¼|Psychic;|Bug;|Rock;|Ghost;|Dragon;|Dark;|Steel;|Fairy;
Rock Grass|Normal;½|Fire;|Water;|Electric;½|Grass;|Ice;2|Fighting;2|Poison;|Ground;|Flying;|Psychic;|Bug;2|Rock;|Ghost;|Dragon;|Dark;|Steel;2|Fairy;
Rock Ice|Normal;½|Fire;|Water;2|Electric;|Grass;2|Ice;½|Fighting;4|Poison;½|Ground;2|Flying;½|Psychic;|Bug;|Rock;2|Ghost;|Dragon;|Dark;|Steel;4|Fairy;
Rock Fighting|Normal;½|Fire;½|Water;2|Electric;|Grass;2|Ice;|Fighting;2|Poison;½|Ground;2|Flying;|Psychic;2|Bug;½|Rock;½|Ghost;|Dragon;|Dark;½|Steel;2|Fairy;2
Rock Poison|Normal;½|Fire;½|Water;2|Electric;|Grass;|Ice;|Fighting;|Poison;¼|Ground;4|Flying;½|Psychic;2|Bug;½|Rock;|Ghost;|Dragon;|Dark;|Steel;2|Fairy;½
Rock Ground|Normal;½|Fire;½|Water;4|Electric;0|Grass;4|Ice;2|Fighting;2|Poison;¼|Ground;2|Flying;½|Psychic;|Bug;|Rock;½|Ghost;|Dragon;|Dark;|Steel;2|Fairy;
Rock Flying|Normal;½|Fire;½|Water;2|Electric;2|Grass;|Ice;2|Fighting;|Poison;½|Ground;0|Flying;½|Psychic;|Bug;½|Rock;2|Ghost;|Dragon;|Dark;|Steel;2|Fairy;
Rock Psychic|Normal;½|Fire;½|Water;2|Electric;|Grass;2|Ice;|Fighting;|Poison;½|Ground;2|Flying;½|Psychic;½|Bug;2|Rock;|Ghost;2|Dragon;|Dark;2|Steel;2|Fairy;
Rock Bug|Normal;½|Fire;|Water;2|Electric;|Grass;|Ice;|Fighting;|Poison;½|Ground;|Flying;|Psychic;|Bug;|Rock;2|Ghost;|Dragon;|Dark;|Steel;2|Fairy;
Rock Ghost|Normal;0|Fire;½|Water;2|Electric;|Grass;2|Ice;|Fighting;0|Poison;¼|Ground;2|Flying;½|Psychic;|Bug;½|Rock;|Ghost;2|Dragon;|Dark;2|Steel;2|Fairy;
Rock Dragon|Normal;½|Fire;¼|Water;|Electric;½|Grass;|Ice;2|Fighting;2|Poison;½|Ground;2|Flying;½|Psychic;|Bug;|Rock;|Ghost;|Dragon;2|Dark;|Steel;2|Fairy;2
Rock Dark|Normal;½|Fire;½|Water;2|Electric;|Grass;2|Ice;|Fighting;4|Poison;½|Ground;2|Flying;½|Psychic;0|Bug;2|Rock;|Ghost;½|Dragon;|Dark;½|Steel;2|Fairy;2
Rock Steel|Normal;¼|Fire;|Water;2|Electric;|Grass;|Ice;½|Fighting;4|Poison;0|Ground;4|Flying;¼|Psychic;½|Bug;½|Rock;½|Ghost;|Dragon;½|Dark;|Steel;|Fairy;½
Rock Fairy|Normal;½|Fire;½|Water;2|Electric;|Grass;2|Ice;|Fighting;|Poison;|Ground;2|Flying;½|Psychic;|Bug;½|Rock;|Ghost;|Dragon;0|Dark;½|Steel;4|Fairy;
Ghost —|Normal;0|Fire;|Water;|Electric;|Grass;|Ice;|Fighting;0|Poison;½|Ground;|Flying;|Psychic;|Bug;½|Rock;|Ghost;2|Dragon;|Dark;2|Steel;|Fairy;
Ghost Normal|Normal;0|Fire;|Water;|Electric;|Grass;|Ice;|Fighting;0|Poison;½|Ground;|Flying;|Psychic;|Bug;½|Rock;|Ghost;0|Dragon;|Dark;2|Steel;|Fairy;
Ghost Fire|Normal;0|Fire;½|Water;2|Electric;|Grass;½|Ice;½|Fighting;0|Poison;½|Ground;2|Flying;|Psychic;|Bug;¼|Rock;2|Ghost;2|Dragon;|Dark;2|Steel;½|Fairy;½
Ghost Water|Normal;0|Fire;½|Water;½|Electric;2|Grass;2|Ice;½|Fighting;0|Poison;½|Ground;|Flying;|Psychic;|Bug;½|Rock;|Ghost;2|Dragon;|Dark;2|Steel;½|Fairy;
Ghost Electric|Normal;0|Fire;|Water;|Electric;½|Grass;|Ice;|Fighting;0|Poison;½|Ground;2|Flying;½|Psychic;|Bug;½|Rock;|Ghost;2|Dragon;|Dark;2|Steel;½|Fairy;
Ghost Grass|Normal;0|Fire;2|Water;½|Electric;½|Grass;½|Ice;2|Fighting;0|Poison;|Ground;½|Flying;2|Psychic;|Bug;|Rock;|Ghost;2|Dragon;|Dark;2|Steel;|Fairy;
Ghost Ice|Normal;0|Fire;2|Water;|Electric;|Grass;|Ice;½|Fighting;0|Poison;½|Ground;|Flying;|Psychic;|Bug;½|Rock;2|Ghost;2|Dragon;|Dark;2|Steel;2|Fairy;
Ghost Fighting|Normal;0|Fire;|Water;|Electric;|Grass;|Ice;|Fighting;0|Poison;½|Ground;|Flying;2|Psychic;2|Bug;¼|Rock;½|Ghost;2|Dragon;|Dark;|Steel;|Fairy;2
Ghost Poison|Normal;0|Fire;|Water;|Electric;|Grass;½|Ice;|Fighting;0|Poison;¼|Ground;2|Flying;|Psychic;2|Bug;¼|Rock;|Ghost;2|Dragon;|Dark;2|Steel;|Fairy;½
Ghost Ground|Normal;0|Fire;|Water;2|Electric;0|Grass;2|Ice;2|Fighting;0|Poison;¼|Ground;|Flying;|Psychic;|Bug;½|Rock;½|Ghost;2|Dragon;|Dark;2|Steel;|Fairy;
Ghost Flying|Normal;0|Fire;|Water;|Electric;2|Grass;½|Ice;2|Fighting;0|Poison;½|Ground;0|Flying;|Psychic;|Bug;¼|Rock;2|Ghost;2|Dragon;|Dark;2|Steel;|Fairy;
Ghost Psychic|Normal;0|Fire;|Water;|Electric;|Grass;|Ice;|Fighting;0|Poison;½|Ground;|Flying;|Psychic;½|Bug;|Rock;|Ghost;4|Dragon;|Dark;4|Steel;|Fairy;
Ghost Bug|Normal;0|Fire;2|Water;|Electric;|Grass;½|Ice;|Fighting;0|Poison;½|Ground;½|Flying;2|Psychic;|Bug;½|Rock;2|Ghost;2|Dragon;|Dark;2|Steel;|Fairy;
Ghost Rock|Normal;0|Fire;½|Water;2|Electric;|Grass;2|Ice;|Fighting;0|Poison;¼|Ground;2|Flying;½|Psychic;|Bug;½|Rock;|Ghost;2|Dragon;|Dark;2|Steel;2|Fairy;
Ghost Dragon|Normal;0|Fire;½|Water;½|Electric;½|Grass;½|Ice;2|Fighting;0|Poison;½|Ground;|Flying;|Psychic;|Bug;½|Rock;|Ghost;2|Dragon;2|Dark;2|Steel;|Fairy;2
Ghost Dark|Normal;0|Fire;|Water;|Electric;|Grass;|Ice;|Fighting;0|Poison;½|Ground;|Flying;|Psychic;0|Bug;|Rock;|Ghost;|Dragon;|Dark;|Steel;|Fairy;2
Ghost Steel|Normal;0|Fire;2|Water;|Electric;|Grass;½|Ice;½|Fighting;0|Poison;0|Ground;2|Flying;½|Psychic;½|Bug;¼|Rock;½|Ghost;2|Dragon;½|Dark;2|Steel;½|Fairy;½
Ghost Fairy|Normal;0|Fire;|Water;|Electric;|Grass;|Ice;|Fighting;0|Poison;|Ground;|Flying;|Psychic;|Bug;¼|Rock;|Ghost;2|Dragon;0|Dark;|Steel;2|Fairy;
Dragon —|Normal;|Fire;½|Water;½|Electric;½|Grass;½|Ice;2|Fighting;|Poison;|Ground;|Flying;|Psychic;|Bug;|Rock;|Ghost;|Dragon;2|Dark;|Steel;|Fairy;2
Dragon Normal|Normal;|Fire;½|Water;½|Electric;½|Grass;½|Ice;2|Fighting;2|Poison;|Ground;|Flying;|Psychic;|Bug;|Rock;|Ghost;0|Dragon;2|Dark;|Steel;|Fairy;2
Dragon Fire|Normal;|Fire;¼|Water;|Electric;½|Grass;¼|Ice;|Fighting;|Poison;|Ground;2|Flying;|Psychic;|Bug;½|Rock;2|Ghost;|Dragon;2|Dark;|Steel;½|Fairy;
Dragon Water|Normal;|Fire;¼|Water;¼|Electric;|Grass;|Ice;|Fighting;|Poison;|Ground;|Flying;|Psychic;|Bug;|Rock;|Ghost;|Dragon;2|Dark;|Steel;½|Fairy;2
Dragon Electric|Normal;|Fire;½|Water;½|Electric;¼|Grass;½|Ice;2|Fighting;|Poison;|Ground;2|Flying;½|Psychic;|Bug;|Rock;|Ghost;|Dragon;2|Dark;|Steel;½|Fairy;2
Dragon Grass|Normal;|Fire;|Water;¼|Electric;¼|Grass;¼|Ice;4|Fighting;|Poison;2|Ground;½|Flying;2|Psychic;|Bug;2|Rock;|Ghost;|Dragon;2|Dark;|Steel;|Fairy;2
Dragon Ice|Normal;|Fire;|Water;½|Electric;½|Grass;½|Ice;|Fighting;2|Poison;|Ground;|Flying;|Psychic;|Bug;|Rock;2|Ghost;|Dragon;2|Dark;|Steel;2|Fairy;2
Dragon Fighting|Normal;|Fire;½|Water;½|Electric;½|Grass;½|Ice;2|Fighting;|Poison;|Ground;|Flying;2|Psychic;2|Bug;½|Rock;½|Ghost;|Dragon;2|Dark;½|Steel;|Fairy;4
Dragon Poison|Normal;|Fire;½|Water;½|Electric;½|Grass;¼|Ice;2|Fighting;½|Poison;½|Ground;2|Flying;|Psychic;2|Bug;½|Rock;|Ghost;|Dragon;2|Dark;|Steel;|Fairy;
Dragon Ground|Normal;|Fire;½|Water;|Electric;0|Grass;|Ice;4|Fighting;|Poison;½|Ground;|Flying;|Psychic;|Bug;|Rock;½|Ghost;|Dragon;2|Dark;|Steel;|Fairy;2
Dragon Flying|Normal;|Fire;½|Water;½|Electric;|Grass;¼|Ice;4|Fighting;½|Poison;|Ground;0|Flying;|Psychic;|Bug;½|Rock;2|Ghost;|Dragon;2|Dark;|Steel;|Fairy;2
Dragon Psychic|Normal;|Fire;½|Water;½|Electric;½|Grass;½|Ice;2|Fighting;½|Poison;|Ground;|Flying;|Psychic;½|Bug;2|Rock;|Ghost;2|Dragon;2|Dark;2|Steel;|Fairy;2
Dragon Bug|Normal;|Fire;|Water;½|Electric;½|Grass;¼|Ice;2|Fighting;½|Poison;|Ground;½|Flying;2|Psychic;|Bug;|Rock;2|Ghost;|Dragon;2|Dark;|Steel;|Fairy;2
Dragon Rock|Normal;½|Fire;¼|Water;|Electric;½|Grass;|Ice;2|Fighting;2|Poison;½|Ground;2|Flying;½|Psychic;|Bug;|Rock;|Ghost;|Dragon;2|Dark;|Steel;2|Fairy;2
Dragon Ghost|Normal;0|Fire;½|Water;½|Electric;½|Grass;½|Ice;2|Fighting;0|Poison;½|Ground;|Flying;|Psychic;|Bug;½|Rock;|Ghost;2|Dragon;2|Dark;2|Steel;|Fairy;2
Dragon Dark|Normal;|Fire;½|Water;½|Electric;½|Grass;½|Ice;2|Fighting;2|Poison;|Ground;|Flying;|Psychic;0|Bug;2|Rock;|Ghost;½|Dragon;2|Dark;½|Steel;|Fairy;4
Dragon Steel|Normal;½|Fire;|Water;½|Electric;½|Grass;¼|Ice;|Fighting;2|Poison;0|Ground;2|Flying;½|Psychic;½|Bug;½|Rock;½|Ghost;|Dragon;|Dark;|Steel;½|Fairy;
Dragon Fairy|Normal;|Fire;½|Water;½|Electric;½|Grass;½|Ice;2|Fighting;½|Poison;2|Ground;|Flying;|Psychic;|Bug;½|Rock;|Ghost;|Dragon;0|Dark;½|Steel;2|Fairy;2
Dark —|Normal;|Fire;|Water;|Electric;|Grass;|Ice;|Fighting;2|Poison;|Ground;|Flying;|Psychic;0|Bug;2|Rock;|Ghost;½|Dragon;|Dark;½|Steel;|Fairy;2
Dark Normal|Normal;|Fire;|Water;|Electric;|Grass;|Ice;|Fighting;4|Poison;|Ground;|Flying;|Psychic;0|Bug;2|Rock;|Ghost;0|Dragon;|Dark;½|Steel;|Fairy;2
Dark Fire|Normal;|Fire;½|Water;2|Electric;|Grass;½|Ice;½|Fighting;2|Poison;|Ground;2|Flying;|Psychic;0|Bug;|Rock;2|Ghost;½|Dragon;|Dark;½|Steel;½|Fairy;
Dark Water|Normal;|Fire;½|Water;½|Electric;2|Grass;2|Ice;½|Fighting;2|Poison;|Ground;|Flying;|Psychic;0|Bug;2|Rock;|Ghost;½|Dragon;|Dark;½|Steel;½|Fairy;2
Dark Electric|Normal;|Fire;|Water;|Electric;½|Grass;|Ice;|Fighting;2|Poison;|Ground;2|Flying;½|Psychic;0|Bug;2|Rock;|Ghost;½|Dragon;|Dark;½|Steel;½|Fairy;2
Dark Grass|Normal;|Fire;2|Water;½|Electric;½|Grass;½|Ice;2|Fighting;2|Poison;2|Ground;½|Flying;2|Psychic;0|Bug;4|Rock;|Ghost;½|Dragon;|Dark;½|Steel;|Fairy;2
Dark Ice|Normal;|Fire;2|Water;|Electric;|Grass;|Ice;½|Fighting;4|Poison;|Ground;|Flying;|Psychic;0|Bug;2|Rock;2|Ghost;½|Dragon;|Dark;½|Steel;2|Fairy;2
Dark Fighting|Normal;|Fire;|Water;|Electric;|Grass;|Ice;|Fighting;2|Poison;|Ground;|Flying;2|Psychic;0|Bug;|Rock;½|Ghost;½|Dragon;|Dark;¼|Steel;|Fairy;4
Dark Poison|Normal;|Fire;|Water;|Electric;|Grass;½|Ice;|Fighting;|Poison;½|Ground;2|Flying;|Psychic;0|Bug;|Rock;|Ghost;½|Dragon;|Dark;½|Steel;|Fairy;
Dark Ground|Normal;|Fire;|Water;2|Electric;0|Grass;2|Ice;2|Fighting;2|Poison;½|Ground;|Flying;|Psychic;0|Bug;2|Rock;½|Ghost;½|Dragon;|Dark;½|Steel;|Fairy;2
Dark Flying|Normal;|Fire;|Water;|Electric;2|Grass;½|Ice;2|Fighting;|Poison;|Ground;0|Flying;|Psychic;0|Bug;|Rock;2|Ghost;½|Dragon;|Dark;½|Steel;|Fairy;2
Dark Psychic|Normal;|Fire;|Water;|Electric;|Grass;|Ice;|Fighting;|Poison;|Ground;|Flying;|Psychic;0|Bug;4|Rock;|Ghost;|Dragon;|Dark;|Steel;|Fairy;2
Dark Bug|Normal;|Fire;2|Water;|Electric;|Grass;½|Ice;|Fighting;|Poison;|Ground;½|Flying;2|Psychic;0|Bug;2|Rock;2|Ghost;½|Dragon;|Dark;½|Steel;|Fairy;2
Dark Rock|Normal;½|Fire;½|Water;2|Electric;|Grass;2|Ice;|Fighting;4|Poison;½|Ground;2|Flying;½|Psychic;0|Bug;2|Rock;|Ghost;½|Dragon;|Dark;½|Steel;2|Fairy;2
Dark Ghost|Normal;0|Fire;|Water;|Electric;|Grass;|Ice;|Fighting;0|Poison;½|Ground;|Flying;|Psychic;0|Bug;|Rock;|Ghost;|Dragon;|Dark;|Steel;|Fairy;2
Dark Dragon|Normal;|Fire;½|Water;½|Electric;½|Grass;½|Ice;2|Fighting;2|Poison;|Ground;|Flying;|Psychic;0|Bug;2|Rock;|Ghost;½|Dragon;2|Dark;½|Steel;|Fairy;4
Dark Steel|Normal;½|Fire;2|Water;|Electric;|Grass;½|Ice;½|Fighting;4|Poison;0|Ground;2|Flying;½|Psychic;0|Bug;|Rock;½|Ghost;½|Dragon;½|Dark;½|Steel;½|Fairy;
Dark Fairy|Normal;|Fire;|Water;|Electric;|Grass;|Ice;|Fighting;|Poison;2|Ground;|Flying;|Psychic;0|Bug;|Rock;|Ghost;½|Dragon;0|Dark;¼|Steel;2|Fairy;2
Steel —|Normal;½|Fire;2|Water;|Electric;|Grass;½|Ice;½|Fighting;2|Poison;0|Ground;2|Flying;½|Psychic;½|Bug;½|Rock;½|Ghost;|Dragon;½|Dark;|Steel;½|Fairy;½
Steel Normal|Normal;½|Fire;2|Water;|Electric;|Grass;½|Ice;½|Fighting;4|Poison;0|Ground;2|Flying;½|Psychic;½|Bug;½|Rock;½|Ghost;0|Dragon;½|Dark;|Steel;½|Fairy;½
Steel Fire|Normal;½|Fire;|Water;2|Electric;|Grass;¼|Ice;¼|Fighting;2|Poison;0|Ground;4|Flying;½|Psychic;½|Bug;¼|Rock;|Ghost;|Dragon;½|Dark;|Steel;¼|Fairy;¼
Steel Water|Normal;½|Fire;|Water;½|Electric;2|Grass;|Ice;¼|Fighting;2|Poison;0|Ground;2|Flying;½|Psychic;½|Bug;½|Rock;½|Ghost;|Dragon;½|Dark;|Steel;¼|Fairy;½
Steel Electric|Normal;½|Fire;2|Water;|Electric;½|Grass;½|Ice;½|Fighting;2|Poison;0|Ground;4|Flying;¼|Psychic;½|Bug;½|Rock;½|Ghost;|Dragon;½|Dark;|Steel;¼|Fairy;½
Steel Grass|Normal;½|Fire;4|Water;½|Electric;½|Grass;¼|Ice;|Fighting;2|Poison;0|Ground;|Flying;|Psychic;½|Bug;|Rock;½|Ghost;|Dragon;½|Dark;|Steel;½|Fairy;½
Steel Ice|Normal;½|Fire;4|Water;|Electric;|Grass;½|Ice;¼|Fighting;4|Poison;0|Ground;2|Flying;½|Psychic;½|Bug;½|Rock;|Ghost;|Dragon;½|Dark;|Steel;|Fairy;½
Steel Fighting|Normal;½|Fire;2|Water;|Electric;|Grass;½|Ice;½|Fighting;2|Poison;0|Ground;2|Flying;|Psychic;|Bug;¼|Rock;¼|Ghost;|Dragon;½|Dark;½|Steel;½|Fairy;
Steel Poison|Normal;½|Fire;2|Water;|Electric;|Grass;¼|Ice;½|Fighting;|Poison;0|Ground;4|Flying;½|Psychic;|Bug;¼|Rock;½|Ghost;|Dragon;½|Dark;|Steel;½|Fairy;¼
Steel Ground|Normal;½|Fire;2|Water;2|Electric;0|Grass;|Ice;|Fighting;2|Poison;0|Ground;2|Flying;½|Psychic;½|Bug;½|Rock;¼|Ghost;|Dragon;½|Dark;|Steel;½|Fairy;½
Steel Flying|Normal;½|Fire;2|Water;|Electric;2|Grass;¼|Ice;|Fighting;|Poison;0|Ground;0|Flying;½|Psychic;½|Bug;¼|Rock;|Ghost;|Dragon;½|Dark;|Steel;½|Fairy;½
Steel Psychic|Normal;½|Fire;2|Water;|Electric;|Grass;½|Ice;½|Fighting;|Poison;0|Ground;2|Flying;½|Psychic;¼|Bug;|Rock;½|Ghost;2|Dragon;½|Dark;2|Steel;½|Fairy;½
Steel Bug|Normal;½|Fire;4|Water;|Electric;|Grass;¼|Ice;½|Fighting;|Poison;0|Ground;|Flying;|Psychic;½|Bug;½|Rock;|Ghost;|Dragon;½|Dark;|Steel;½|Fairy;½
Steel Rock|Normal;¼|Fire;|Water;2|Electric;|Grass;|Ice;½|Fighting;4|Poison;0|Ground;4|Flying;¼|Psychic;½|Bug;½|Rock;½|Ghost;|Dragon;½|Dark;|Steel;|Fairy;½
Steel Ghost|Normal;0|Fire;2|Water;|Electric;|Grass;½|Ice;½|Fighting;0|Poison;0|Ground;2|Flying;½|Psychic;½|Bug;¼|Rock;½|Ghost;2|Dragon;½|Dark;2|Steel;½|Fairy;½
Steel Dragon|Normal;½|Fire;|Water;½|Electric;½|Grass;¼|Ice;|Fighting;2|Poison;0|Ground;2|Flying;½|Psychic;½|Bug;½|Rock;½|Ghost;|Dragon;|Dark;|Steel;½|Fairy;
Steel Dark|Normal;½|Fire;2|Water;|Electric;|Grass;½|Ice;½|Fighting;4|Poison;0|Ground;2|Flying;½|Psychic;0|Bug;|Rock;½|Ghost;½|Dragon;½|Dark;½|Steel;½|Fairy;
Steel Fairy|Normal;½|Fire;2|Water;|Electric;|Grass;½|Ice;½|Fighting;|Poison;0|Ground;2|Flying;½|Psychic;½|Bug;¼|Rock;½|Ghost;|Dragon;0|Dark;½|Steel;|Fairy;½
Fairy —|Normal;|Fire;|Water;|Electric;|Grass;|Ice;|Fighting;½|Poison;2|Ground;|Flying;|Psychic;|Bug;½|Rock;|Ghost;|Dragon;0|Dark;½|Steel;2|Fairy;
Fairy Normal|Normal;|Fire;|Water;|Electric;|Grass;|Ice;|Fighting;|Poison;2|Ground;|Flying;|Psychic;|Bug;½|Rock;|Ghost;0|Dragon;0|Dark;½|Steel;2|Fairy;
Fairy Fire|Normal;|Fire;½|Water;2|Electric;|Grass;½|Ice;½|Fighting;½|Poison;2|Ground;2|Flying;|Psychic;|Bug;¼|Rock;2|Ghost;|Dragon;0|Dark;½|Steel;|Fairy;½
Fairy Water|Normal;|Fire;½|Water;½|Electric;2|Grass;2|Ice;½|Fighting;½|Poison;2|Ground;|Flying;|Psychic;|Bug;½|Rock;|Ghost;|Dragon;0|Dark;½|Steel;|Fairy;
Fairy Electric|Normal;|Fire;|Water;|Electric;½|Grass;|Ice;|Fighting;½|Poison;2|Ground;2|Flying;½|Psychic;|Bug;½|Rock;|Ghost;|Dragon;0|Dark;½|Steel;|Fairy;
Fairy Grass|Normal;|Fire;2|Water;½|Electric;½|Grass;½|Ice;2|Fighting;½|Poison;4|Ground;½|Flying;2|Psychic;|Bug;|Rock;|Ghost;|Dragon;0|Dark;½|Steel;2|Fairy;
Fairy Ice|Normal;|Fire;2|Water;|Electric;|Grass;|Ice;½|Fighting;|Poison;2|Ground;|Flying;|Psychic;|Bug;½|Rock;2|Ghost;|Dragon;0|Dark;½|Steel;4|Fairy;
Fairy Fighting|Normal;|Fire;|Water;|Electric;|Grass;|Ice;|Fighting;½|Poison;2|Ground;|Flying;2|Psychic;2|Bug;¼|Rock;½|Ghost;|Dragon;0|Dark;¼|Steel;2|Fairy;2
Fairy Poison|Normal;|Fire;|Water;|Electric;|Grass;½|Ice;|Fighting;¼|Poison;|Ground;2|Flying;|Psychic;2|Bug;¼|Rock;|Ghost;|Dragon;0|Dark;½|Steel;2|Fairy;½
Fairy Ground|Normal;|Fire;|Water;2|Electric;0|Grass;2|Ice;2|Fighting;½|Poison;|Ground;|Flying;|Psychic;|Bug;½|Rock;½|Ghost;|Dragon;0|Dark;½|Steel;2|Fairy;
Fairy Flying|Normal;|Fire;|Water;|Electric;2|Grass;½|Ice;2|Fighting;¼|Poison;2|Ground;0|Flying;|Psychic;|Bug;¼|Rock;2|Ghost;|Dragon;0|Dark;½|Steel;2|Fairy;
Fairy Psychic|Normal;|Fire;|Water;|Electric;|Grass;|Ice;|Fighting;¼|Poison;2|Ground;|Flying;|Psychic;½|Bug;|Rock;|Ghost;2|Dragon;0|Dark;|Steel;2|Fairy;
Fairy Bug|Normal;|Fire;2|Water;|Electric;|Grass;½|Ice;|Fighting;¼|Poison;2|Ground;½|Flying;2|Psychic;|Bug;½|Rock;2|Ghost;|Dragon;0|Dark;½|Steel;2|Fairy;
Fairy Rock|Normal;½|Fire;½|Water;2|Electric;|Grass;2|Ice;|Fighting;|Poison;|Ground;2|Flying;½|Psychic;|Bug;½|Rock;|Ghost;|Dragon;0|Dark;½|Steel;4|Fairy;
Fairy Ghost|Normal;0|Fire;|Water;|Electric;|Grass;|Ice;|Fighting;0|Poison;|Ground;|Flying;|Psychic;|Bug;¼|Rock;|Ghost;2|Dragon;0|Dark;|Steel;2|Fairy;
Fairy Dragon|Normal;|Fire;½|Water;½|Electric;½|Grass;½|Ice;2|Fighting;½|Poison;2|Ground;|Flying;|Psychic;|Bug;½|Rock;|Ghost;|Dragon;0|Dark;½|Steel;2|Fairy;2
Fairy Dark|Normal;|Fire;|Water;|Electric;|Grass;|Ice;|Fighting;|Poison;2|Ground;|Flying;|Psychic;0|Bug;|Rock;|Ghost;½|Dragon;0|Dark;¼|Steel;2|Fairy;2
Fairy Steel|Normal;½|Fire;2|Water;|Electric;|Grass;½|Ice;½|Fighting;|Poison;0|Ground;2|Flying;½|Psychic;½|Bug;¼|Rock;½|Ghost;|Dragon;0|Dark;½|Steel;|Fairy;½";
?>